### ISSUE TITLE
checksum-compute keeps timing out for rm242zg2446

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#1005]
**Describe the bug**
One druid has been repeatedly hitting a timeout error at the checksum-compute step in the assemblyWF: https://argo.stanford.edu/view/druid:rm242zg2446

` Error: checksum-compute : Net::ReadTimeout with #<TCPSocket:(closed)>`
https://app.honeybadger.io/projects/52894/faults/88727290

I haven't been able to figure out where the problem is. This step can take 12-24 hours for large files (over 1 TB) and I've never seen it time out before. I've tried pausing google-books and resetting the step while the system is less busy in the hope that the step would run faster but the time out still occurred.

My suspicion is that the problem may be related to the number of files. This object has 25,385 files (a roughly 6300 page publication), which makes it one of the larger objects in the SDR in terms of number of files.

**User Impact**
This is blocking accessioning as the step cannot be skipped or marked complete. This step creates the checksums in the Cocina metadata that are required for accessioning.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:rm242zg2446
2. Reset the step
3. Wait about 2 hours
4. See the error

**Additional context**
It's possible that this object will hit timeouts at later steps too. Depending on the step, it may or may not work to reset the step or manually mark it completed.

**Comment by peetucket** [comment]
The HB alert suggests that the checksum computation finished and then it tried to post a giant blob of updated cocina via the dor-services-client (here: https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/assembly/checksum_compute.rb#L18), this resulted in a dor-services-app call (made by dor-services-client), which then timed out.  One possibility is setting a long timeout in the dor-services-client to allow this big update more time to complete?

Basically, add `builder.options[:timeout] = 600 # 10 minutes timeout to wait for a response'

here: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client.rb#L155-L158
 
I'm not sure what the default is (docs say Faraday does not impose one), but this suggests the default timeout of the Net:HTTP adapter used is only 60 seconds: https://github.com/lostisland/faraday/issues/708

And your suspicion about future steps failing is a good one -- the next step is exif-collect, which will likely fail in the same way.

**Comment by peetucket** [comment]
Producing the file set checksums manually now on the common-accessioning box.  Will then move the data that is posted to DSA and try and perform the update manually on the DSA server to see what happens.

```
ROBOT_ENVIRONMENT=production bin/console
druid='druid:rm242zg2446'
assembly_item = Dor::Assembly::Item.new druid: druid
cocina_model = assembly_item.cocina_model # this takes like 45 seconds!

# copy and paste the compute_checksums and checksums_equal? methods into the console from
https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/assembly/checksum_compute.rb#L24-L60

file_sets = compute_checksums(assembly_item, cocina_model) # this took about 1 hour and produced data to save (which would have just been posted to DSA)
```

**Comment by peetucket** [comment]
This object has made it through assemblyWF and accessionWF.  It may still encounter issues in preservation (we shall see), but I'm closing this ticket as if there are further issues, they are unlikely to be related to the problem I fixed here.
