### ISSUE TITLE
Verify required checksums before finishing checksum-compute (assemblyWF)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#1056]
**Describe the bug**
In the assemblyWF, there is a step called `checksum-compute`. I think this step does at least two things:

1. Validates checksums that have been provided if a user does that
2. Generates checksums for any and all files that lack the required checksums at this point

There are two types of required checksums at this point in accessioning:

1. md5
2. sha1

If these checksums are not generated by the end of `checksum-compute` then accessioning will eventually fail. Other steps later in the accessionWF rely on having both types of checksums present in the Cocina. The Moab will also require these checksums, plus add sha256 as well.

**User Impact**
When md5 and/or sha1 checksums are missing and the workflow continues on, the resulting error messages can be quite misleading, causing delays in resolving the issue.

For example, a recent occurrence of this error happened during the `shelve` step and made it look like the problem was in preservation. The `shelve` step looked for the required checksums, could not find them, and reported a message implying that the issue had to do with the "content diff" where files being accessioned are compared with files already preserved. But the problem had nothing to do with preservation because the issue occurred on the very first version of the object, which by definition has not yet been preserved.

**To Reproduce**
It's not clear how to reproduce this. Very occasionally, files go through assemblyWF without getting md5 and/or sha1 checksums. Maybe it's a problem more likely to occur when the system is very busy.

**Expected behavior**
`checksum-compute` should compute the required checksums. If that fails, then the step should should report an error. This will allow people to retry from the Argo UI and avoid someone having to go through a bunch of workflow server rake task rigamarole to resolve things.

**Additional context**
We'll have to be careful with validation timing. Some files (such as auto-generated JP2s) will start `checksum-compute` without checksums, so those shouldn't cause an error. The error should only be triggered if checksums are still missing when the step is about to be marked complete.

**Comment by mjgiarlo** [comment]
@andrewjbtw I've spelunked a bit in common-accessioning and assembly-objectfile and, as best I can tell, it should not be possible for this step to be completed without valid MD5 and SHA1 checksums for every file. This may be a good one to pair on if we don't have any sample druids handy.

**Comment by andrewjbtw** [comment]
I think I can get the data from one of the recent druids that had this error into stage and see if that can help reproduce it. It's possible that what's happening is a result of accessioning being run a second time on a druid already in an error state, with unexpected results. This has happened a few times in the past few months, but IIRC it's always been a case where a druid had some other problem first.

**Comment by mjgiarlo** [comment]
@andrewjbtw OK, sounds good. Thanks!

**Comment by peetucket** [comment]
Just reviving this to see if we need the fix in https://github.com/sul-dlss/common-accessioning/pull/1062 ... it is already approved, so can easily be merged, unless we think this is a non-issue that is the result of other data problems.

**Comment by mjgiarlo** [comment]
@peetucket 💬 
> Just reviving this to see if we need the fix in #1062 ... it is already approved, so can easily be merged, unless we think this is a non-issue that is the result of other data problems.

Question for Andrew?
