### ISSUE TITLE
Support targeted file updates for exif collection robot

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#1092]
Currently the exif collection robot determines the size, mimetype, and optionally the image dimensions for each file.

With targeted file updates, the file may not exist in the workspace.

To support targeted file updates, if the file does not existing in the workspace and the cocina file already has a size and mimetype then ignore.

**Comment by edsu** [comment]
I didn't get to this today as planned, so I thought I would put it back in Ready in case someone else wanted at it before tomorrow.
