### ISSUE TITLE
no longer a need for Lane items to be treated as special

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#1104]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmErIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--886a26ca11f1d6e84d1c50e4e49c3b1396f24603/image.png)

I know we have priority "lanes" for Lane items in some of our sidekiq configurations, and in our code.  These can now all be removed!

woo hoo!  simpler code!

I think doing a github search of sul-dlss, or a search of all the infra repos stored locally on your machine would be a good way to find all of this ...

**Comment by justinlittman** [comment]
@ndushay Can you give an example / more of a hint of what these might be?

**Comment by ndushay** [comment]
here are at least some of them:  https://github.com/search?q=repo%3Asul-dlss%2Fcommon-accessioning%20lane&type=code

**Comment by andrewjbtw** [comment]
Wait, aren't those the prioritization queues that allow us to do things like keep Google Books behind regular accessioning?

**Comment by ndushay** [comment]
so it's not Lane the library, but "lane" the priority?   That isn't confusing at all.   I'm also not sure that's the only place.

**Comment by ndushay** [comment]
okay, this is already done.  "lane" is about priority.
