### ISSUE TITLE
jp2-create should not overwrite jp2s that already exist in the /dor/assembly tree

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#1112]
**Describe the bug**
The `jp2-create` step is supposed to leave JP2 files alone if they've already been created in the `/dor/assembly` tree for the druid being processed. This makes it possible for the step to continue where it left off it it's interrupted while creating JP2s for a long list of files. It also makes it possible to fix errors in JP2 creation by bypassing the automatic image creation and supplying a new JP2 file.

While re-seeding stage after the reset, I've noticed that `jp2-create` is ovewriting JP2 files that were already created in the reset. The sequence of events has been this:

- `jp2-create` starts
- JP2 files are created for a few dozen TIFFs
- `jp2-create` is interrupted
- `jp2-create` is started again
- New JP2s are created for all of the TIFFs, including ones where JP2s had already been created

**User Impact**
There may be a risk that when a user supplies their own JP2s, they will be overwritten by the workflow step.

**To Reproduce**
I don't have a live example in stage but I think these steps would do it:
1. Start a Preassembly job with multiple images
2. Interrupt the workflow step at `jp2-create` after some JP2s are created
3. Set `jp2-create` back to "waiting" and requeue it
4. See that the JP2 get overwritten

**Expected behavior**
If a JP2 exists in /dor/assembly, don't overwrite it.

**Comment by justinlittman** [comment]
@andrewjbtw Is this fixed?
