### ISSUE TITLE
Split OCR full document XML into page level XML

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1176]
Write implementation for `ocrWF:split-ocr-xml` robot (see example code below in comments)

ABBYY will create either page level OCR XML or full document OCR XML, but not both.  We want both so the viewer can offer full text search and hit highlighting by page.  

The solution is to ask ABBYY to produce only full document XML and then split it ourselves into page level.  We tested that this will work and have a ruby script below that was used to do the split for the test.

This will be easier to do when we have actual ABBYY output

**Comment by jmartin-sul** [comment]
@peetucket may have some example files he can attach to this ticket for use in manual testing and/or unit test fixtures.  and once we start producing OCR output, we'll have many more examples to work with.

this needs to work for books with multiple images, and items with multiple images.  but ABBYY is unaware of our object structures, and just knows it gets multiple images, which it treats as individual pages?  ABBYY gets the order of pages/filenames from the order of the files listed in the ABBYY XML ticket.
