### ISSUE TITLE
Re-stage content from OCR output

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1177]
Write implementation for `ocrWF:stage-files` robot

The new caption and OCR robots will be creating new files that will be added to the content folder being accessioned.  

Create a new robot to re-stage the files that came out of OCR in /dor/workspace

Note: closing the version in the last step of ocrWF will kick off accessioning

**Comment by jmartin-sul** [comment]
This robot will likely have to read the existing Cocina and use that in combination with the OCR output to determine which files are being replaced and which files are being added.  depends on

**Comment by jmartin-sul** [comment]
We think this also might sort of depend on or overlap with #1185, so if two different people pick up these two tickets, they should maybe coordinate.
