### ISSUE TITLE
Copy files to be OCRed from preservation

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1187]
part of #1166 (ocrWF:ocr-create)

Blocked by #1188
Since we will be running ocrWF after accessionWF has been run, all of the files have already been cleared off the workspace.  In order to run OCR, we will need to get the files from preservation and put them in the ABBYY watch folder.

So we need to fetch files from preservation and move them to ABBYY

**Comment by dnoneill** [comment]
It looks like the original file gets preserved but not the jp2. I am assuming we either need to figure out where JP2 is stored or we need to preserve all jp2s?

**Comment by peetucket** [comment]
That's a good point.  I think the only time we'd expect a situation like this is where we have both a derivative JP2 and an original TIFF, in which case we only need one of these to do the OCR (e.g. the original TIFF), which would be preserved.  If there was no derivative file needed (i.e. input was a JP2), that JP2 should have been preserved.  So I think what is in preservation should always be sufficient for OCR.

However, this raises a good question, which is:

When coming up with a list of files to send to OCR via the XML ticket by inspecting cocina, how do we programmatically determine this list of files?  because if we should just pull all files of a specific mimetype, we will often double the same image (eg jp2 + tiff for the same page).

Any ideas @andrewjbtw or others?

**Comment by edsu** [comment]
Could we only OCR one of the image files (maybe the JP2 since it's smaller) if an TIFF and JP2 appear in the same Cocina resource?

So for example only the `p9261102.jp2` in the Cocina below would be processed:

```json
{
  ...
  "structural": {
    "contains": [
      {
        "structural": {
          "contains": [
            {
              "type": "https://cocina.sul.stanford.edu/models/file",
              "externalidentifier": "https://cocina.sul.stanford.edu/file/cq733gs2535-cq733gs2535_1/p9261102.tif",
              "label": "p9261102.tif",
              "filename": "p9261102.tif",
              "size": 339755,
              "version": 4,
              "hasmimetype": "image/jpeg"
              ...
            },
            {
              "type": "https://cocina.sul.stanford.edu/models/file",
              "externalidentifier": "https://cocina.sul.stanford.edu/file/cq733gs2535-cq733gs2535_1/p9261102.jp2",
              "label": "p9261102.jp2",
              "filename": "p9261102.jp2",
              "size": 361536,
              "version": 4,
              "hasmimetype": "image/jp2"
              ...
            }
          ]
        }
      },
      {
          ... another resource
      }
    ]
  }
}
```

**Comment by dnoneill** [comment]
I would assume no because the JP2 isn't on the preservation stack.

**Comment by edsu** [comment]
I think @peetucket's question was about if there were both available, how would you choose?

**Comment by peetucket** [comment]
It may be a safe assumption that only one file per resource is required (each resource represents new content, and the multiple files within a resource are just different formats of that same content?). 

In which case, maybe a preferential order to select just one file (i.e. tiff before jp2 before jpeg or something like that)?

**Comment by edsu** [comment]
I imagine that @andrewjbtw has the best sense of whether we can rely on *resources* or file groups this way.

**Comment by edsu** [comment]
I went ahead and closed https://github.com/sul-dlss/operations-tasks/issues/3746 with the idea of trying to use prescat API for the files first, and falling back to using the mounted preservation file system as a plan B.

**Comment by andrewjbtw** [comment]
We should use the original (preserved, non-JP2) file as the source for ABBYY. That's the set of files we should always have. The text mining use case may involve running OCR on items that are not available to the public and don't have JP2s. In those cases, we are permitted to deliver OCR by sharing directly with the requestor, which means that we should still be able to generate it even in the absence of a public display.

It is true that we have not evaluated difference in performance running ABBYY on JPG/JP2/TIFF, so we could be missing out on some optimization there. Even then, I would argue for generating a derivative off of the preserved file rather than the JP2.

**Comment by peetucket** [comment]
Will it be true that we always expect a TIFF then?  And if there is no TIFF in a resource for an image or book object type, do we just skip that resource, or should we fallback to a JP2?

**Comment by andrewjbtw** [comment]
>It may be a safe assumption that only one file per resource is required (each resource represents new content, and the multiple files within a resource are just different formats of that same content?).

>In which case, maybe a preferential order to select just one file (i.e. tiff before jp2 before jpeg or something like that)?

Yes, that's correct. Every "page" or "image" represents one "unit" of content and the individual files are different representations. If there are multiple image file formats within a resource, they each should show the same visual content.

We can have these combinations:

- TIFF + JP2 (where the TIFF is the preservation file)
- only TIFF (where TIFF is the preservation file, and the item is not public)

- JPG + JP2 (there the JPG is the preservation file)
- only JPG (where JPG is the preservation file, and the item is not public)

- only JP2 (where the JP2 is both the preservation and the display file)
  - this is a rare case, but possible - some third-party partners use JP2 as their digitization target

We may also support PNG + JP2 but I don't think I've ever seen it in production.

**Comment by andrewjbtw** [comment]
Assuming we are talking only about the book/image model here:

- If the resource has only one image type, we should use that.

- If the resource has no image type (i.e. it's just a single PDF, such as the full book PDF from a previous OCR run), we should not send that to ABBYY. But this is where file-level metadata might need to be factored in.

**Comment by peetucket** [comment]
> Assuming we are talking only about the book/image model here:
> 
> * If the resource has only one image type, we should use that.
> * If the resource has no image type (i.e. it's just a single PDF, such as the full book PDF from a previous OCR run), we should not send that to ABBYY. But this is where file-level metadata might need to be factored in.

And?

* If the resource has more than one image type (e.g. TIFF and JP2), preferentially use TIF then JP2

**Comment by edsu** [comment]
> And?
> 
>     * If the resource has more than one image type (e.g. TIFF and JP2), preferentially use TIF then JP2

I'm just noting this here that the logic for what counts as OCRable was done as part of https://github.com/sul-dlss/common-accessioning/issues/1201 This ticket assumes that the `Dor::TextExtraction::Ocr.filenames_to_ocr` method is correct.
