### ISSUE TITLE
Create read only preservation mounts on common accessioning

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1188]
part of #1166 (ocrWF:ocr-create)

We need to be able to copy files from preservation so they can be OCRed.  We expect to be doing this from common accessioning and will need read only mounts to preservation storage

**Comment by edsu** [comment]
This is ticketed in https://github.com/sul-dlss/operations-tasks/issues/3746

**Comment by edsu** [comment]
I decided to give prescat API a try first for retrieving files and will reopen this if that turns into a dead end.
