### ISSUE TITLE
Create mounts to ABBYY folders from accessioning servers

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1192]
We need to mount ABBYY folders so that we can move content for OCRing from the common-accessioning machines.

The docs with some explanation are in drive: https://drive.google.com/drive/u/0/folders/13-mfhKMiWg7A8J7GLnAkH1jLRMXD6HVY We've mostly been using the 'XMLTICKET' method. The short version is you put the .xml file and files in the XMLTICKET folder, the .xml file has the list of files to-be-processed, Abbyy moves them to a temp location, does the processing, and then puts the output files in the OUTPUT location. If there is a problem, the files go into the EXCEPTIONS folder.

https://docs.google.com/document/d/1CcxyAUO92IQfUQRzRtSCChbHAWhJDB3QHIN40D9nqzo/edit#heading=h.i313ss50ap9k

see https://stanfordlib.slack.com/archives/C06EVDJV45N/p1713543265070249

This is likely an Ops task. So this ticket is to ask Ops and monitor progress and then verify

```
smb://WIN;sunetid@dpglab-ocr-a.stanford.edu/dpg-ocr


created sdr-ocr-prod sdr-ocr-qa and sdr-ocr-stage shares and set up Abbyy watched folders for each.
```

**Comment by edsu** [comment]
The ops ticket is here: https://github.com/sul-dlss/operations-tasks/issues/3739

**Comment by jmartin-sul** [comment]
ops ticket done, mounts present, closing
