### ISSUE TITLE
Verify/update logic for when ocrWF should be started

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1203]
Original work to create logic for when start ocrW is in https://github.com/sul-dlss/common-accessioning/pull/1196

1. This may need to be updated once we have cocina-models changed worked out, and the logic for when ocrWF should be started has dependencies on values of some of those attributes.  Changes would be in lib/dor/text_extraction/ocr.rb
2. We may need to update the list of allowed object content types, also defined in this class.
3. We may need to update the list of allowed file mimetypes, also defined in this class.

see https://github.com/sul-dlss/common-accessioning/pull/1196/files#diff-533b023928657eb8023aff46f7eb1788bd62c317045e7d01627d70fe9f58fb42R54-R73

**Comment by jmartin-sul** [comment]
Leaving this open till the end of the work cycle so that we can verify that we got this logic right.  May end up resulting in no changes.
