### ISSUE TITLE
Clear out empty druid subfolder in ABBYY folders

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1212]
After the ocrWF runs and ABBYY is done OCRing, there will be an empty druid subfolder in the ABBYY input folder.  After we stage the files to the dor workspace, we can also delete the ocr files in the ABBYY output folders.  We can delete these folders.

1. Create a new step right before `end-ocr` called `ocr-workspace-cleanup`.  This requires changes to workflow-server-rails (https://github.com/sul-dlss/workflow-server-rails/pull/771)
2. New robot in common-accessioning.
3. Robot should cleanup for the input (if empty0 and output druid subfolders as well as the XML ticket path.  Paths to cleanup can be obtained using an existing class, see https://github.com/sul-dlss/common-accessioning/blob/main/lib/dor/text_extraction/ocr.rb#L15-L21
4. Raise an error if input folder is not empty

See notes: https://docs.google.com/document/d/1ADOY6Mr9pwVf2EUr2wb-dt8_KVUBxMSksrrcY5Qqi5o/edit#heading=h.xvsjlhm036c3

**Comment by jmartin-sul** [comment]
Can listen for event indicating OCR completion, and clean up after that.  Can also have a safeguard that only cleans up empty folders, since we expect ABBYY to delete the input files, and throw an error if there are still files present?

Backlogging till #1191 is done.
