### ISSUE TITLE
Investigate potential race condition in fetch-files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1237]
The fetch-files robot sometimes fails with 404s when running the OCR integration test: https://github.com/sul-dlss/infrastructure-integration-test/pull/731

Speculation is that the files are not yet being returned by the preservation client call, even though we waited for `end-accession` to complete before starting `ocrWF`.  Re-running the step will  eventually get it to succeed.  It may be a coincidence, but it seemed that verifying the files were actually available in preservation in Argo (by clicking the preservation download file link) made it work right away after a retry.

Possible Solution:  Wait for files to be available for a certain amount of time by re-trying the call to Preservation a certain number of times?

**Comment by edsu** [comment]
This makes sense `accessionWF` will kick off `ocrWF` before `preservationWF` has had a chance to finish. It does seem like some kind of back off with logging is appropriate.

**Comment by peetucket** [comment]
Update: download of files via argo seems to be a red herring.  Did another integration test, got the 404, waited ~2 mins, retried the fetch-files step, and it worked.

So, retries seems like it would help, though not explain the lag.

**Comment by edsu** [comment]
From @jmartin-sul in Slack:

> preservationIngestWF starts and finishes within accessionWF, the sdr-ingest-transfer step in accessionWF kicks off preservationWF.

So it seems like it should not be possible for `accessionWF` to kick off `ocrWF` without the files being available via the Preservation API (which is what fetch-files is doing).

Here's what the merged prescat logs look like for a given item while running the new integration test [preassembly_ocr_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/ocr-spec/spec/features/preassembly_ocr_image_spec.rb) integration test. The lines are merged from the two servers that are load balanced: 

```
preservation-catalog-web-qa-02 172.20.21.210 - - [21/May/2024:07:39:18 -0700] "GET /v1/objects/druid:bt801yg0737.json HTTP/1.1" 404 90 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-02 172.20.21.210 - - [21/May/2024:07:39:18 -0700] "GET /v1/objects/druid:bt801yg0737.json HTTP/1.1" 404 90 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-01 172.20.21.210 - - [21/May/2024:07:39:19 -0700] "GET /v1/objects/druid:bt801yg0737/file?category=manifest&filepath=signatureCatalog.xml&version HTTP/1.1" 404 54 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-02 172.20.21.210 - - [21/May/2024:07:39:20 -0700] "GET /v1/objects/druid:bt801yg0737/validate_moab HTTP/1.1" 200 2 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-02 172.20.21.210 - - [21/May/2024:07:39:22 -0700] "GET /v1/objects/druid:bt801yg0737.json HTTP/1.1" 200 145 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-01 172.20.21.210 - - [21/May/2024:07:39:22 -0700] "GET /v1/objects/druid:bt801yg0737.json HTTP/1.1" 200 145 "-" "preservation-client 6.2.0"
preservation-catalog-web-qa-02 172.20.21.210 - - [21/May/2024:07:39:24 -0700] "GET /v1/objects/druid:bt801yg0737/file?category=content&filepath=testocr.tiff&version HTTP/1.1" 200 1232246 "-" "preservation-client 7.0.0"
preservation-catalog-web-qa-01 172.20.21.210 - - [21/May/2024:07:39:24 -0700] "GET /v1/objects/druid:bt801yg0737/file?category=content&filepath=testocr2.tiff&version HTTP/1.1" 404 54 "-" "preservation-client 7.0.0"
```
