### ISSUE TITLE
Write an event to the item's event history when OCR is complete

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1243]
We want to record that ABBYY produced the OCR and any metadata we have about (version?).  This means we should call the SDR event service to record this event.  This can happen in the file watcher process when a druid is known be complete (when we update the ocr-create step to complete).

See what metadata is available in the XML result or ALTO file and see if we can get the version number or other useful info about ABBYY from there

See https://docs.google.com/document/d/1ADOY6Mr9pwVf2EUr2wb-dt8_KVUBxMSksrrcY5Qqi5o/edit#heading=h.k5grpez8plp7

**Comment by andrewjbtw** [comment]
>We want to record that ABBYY produced the OCR and any metadata we have about (version?)

Version of ABBYY.

**Comment by jcoyne** [comment]
@peetucket Does this need to be a separate event?  Could we record this in the workflow step complete message?

**Comment by peetucket** [comment]
> @peetucket Does this need to be a separate event? Could we record this in the workflow step complete message?
> 
> ```ruby
> return LyberCore::ReturnState.new(status: :completed, note: "ABBYY version 1.2.3")
> ```

@andrewjbtw asked for it to be an event, but perhaps this would also be sufficient.

**Comment by andrewjbtw** [comment]
It can go into the workflow service but I would still like it to be recorded as an event. I don't want to lose things in the workflow db where there's no commitment to save that data, and where there have been multiple cases where we ended up overwriting past data. The workflow display also only shows the most recent version of a workflow and you have to dig into the XML to see past info if a workflow has been run more than once.

In contrast, the events are supposed to be a more persistent log of what actions have been taken on an object.
