### ISSUE TITLE
Verify the correct OCR files are being staged

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1261]
Look at https://argo-qa.stanford.edu/view/druid:cp180pg8185 ... this was created via the OCR integration test.

If you look at what was left over in the abbyy folder, you will see two XML files, appearing to be for each image in the object.  We would expect those to have been moved over to the `/dor/workspace` as part of the `ocrWF:stage-files` step, but it doesn't look like they were:

```
lyberadmin@common-accessioning-qa-a:/abbyy/OUTPUT/cp180pg8185$ ls -al
total 24
drwxrwx--- 2 lyberadmin lyberadmin    0 May 31 14:10 .
drwxrwx--- 2 lyberadmin lyberadmin 4096 May 31 14:10 ..
-rw-rw---- 1 lyberadmin lyberadmin 7499 May 31 14:10 testocr2.xml
-rw-rw---- 1 lyberadmin lyberadmin 9887 May 31 14:10 testocr.xml
```

We cannot see what was actually staged to `/dor/workspace` since v2 of accessionWF completed quickly and cleaned out the workspace.

Investigating this may require temporarily and deliberately throwing `ocrWF:end-ocr` to an error state to stop it from proceeding to verify what was actually copied to `/dor/workspace` to see if there is a bug in `ocrWF:stage-files` (or maybe some extra logging of what was copied)

**Comment by edsu** [comment]
I think this was fixed as part of resolving #1266.
