### ISSUE TITLE
See if abbyy or file system can write files with correct permissions

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1271]
Ed noticed during end-to-end testing that Abbyy was generating files with `-rw-rw----` but when preservationIngestWF tried to read the files the files it couldn't.  He noticed other files in `/dor/workspace/` were `-rw-rw-r--`.

This PR adds a chmod to deal with this: https://github.com/sul-dlss/common-accessioning/pull/1264

It would be nice not to have to do this if the files would be written by abbyy with correct permissions in the first place.

Coordinate with ops and Tony C

**Comment by dnoneill** [comment]
Updated puppet

https://github.com/sul-dlss/puppet/pull/10807
https://github.com/sul-dlss/puppet/pull/10832

**Comment by dnoneill** [comment]
I think is working. On qa I created a ticket and copied the files manually for qd239dc9754 and it looks like the permissions in the output file are right.

**Comment by peetucket** [comment]
I think we should remove it if it's not needed.  I don't think we do this anywhere else.  I'll put in a branch to remove the chmod in code, we can then deploy to QA and run the OCR integration test to test.
