### ISSUE TITLE
Request 20 TB of disk space for the /abbyy mount

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1288]
The /abbyy mounts can run out of space when processing ocrWF.  This is temp space that will get cleaned up after processing is complete, so will be bursty, but is important to have.

Question: is this the same mount between qa/stage/prod?

**Comment by peetucket** [comment]
See https://github.com/sul-dlss/operations-tasks/issues/3786

**Comment by andrewjbtw** [comment]
We got 5 TB, closing.
