### ISSUE TITLE
Investigate very slow stage files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1308]
This object has had the split XML step run multiple times (it was the one I was using for testing being able to deal with big XML files since it has ~1200 pages).  Now it appears to be stuck in the stage files step for a day.  We should figure out if there is an issue or if it really takes this long: https://argo-qa.stanford.edu/view/druid:gq110sz4835

**Comment by peetucket** [comment]
This step in stage files seems to be killing the server:

```
abbyy_results = Dor::TextExtraction::Abbyy::Results.find_latest(druid:'gq110sz4835', logger: nil)
```

Likely more nokogiri memory nonsense with large XML files, similar to what we had to do in https://github.com/sul-dlss/common-accessioning/pull/1304

**Comment by edsu** [comment]
It does look like there isn't enough memory on common-accessioning machines in QA to parse the XML without swapping.

When parse isn't running:

<img width="1618" alt="Screenshot 2024-06-24 at 12 31 13 PM" src="https://github.com/sul-dlss/common-accessioning/assets/33829/489d7f6f-e830-4c43-a213-75415dfe7662">

While it is running:

<img width="1618" alt="Screenshot 2024-06-24 at 12 34 21 PM" src="https://github.com/sul-dlss/common-accessioning/assets/33829/134f5b91-dc2a-440f-a3de-b6a77d4b7773">
