### ISSUE TITLE
Finish skeleton common-accessioning robot and workflow def for `speechToTextWF`

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#1341]
The start of the code for this is already there, and assumes the name will be `captionWF`: https://github.com/sul-dlss/common-accessioning/tree/main/lib/robots/dor_repo/caption

But part of this work will be renaming in light of the decision to go with `speechToTextWF`.  See terminology note on https://github.com/sul-dlss-labs/sul_speech_to_text_services/issues/1

The workflow XML is not yet in place, but the skeleton code is already present.

The workflow definition would be a new XML file here: https://github.com/sul-dlss/workflow-server-rails/tree/main/config/workflows

The skeleton workflow with placeholders for steps we expect, with implementations filled in as supporting services are developed, will be similar to what we did for `ocrWF`.

Steps we're likely to have, in order:
- writing media files to S3
- (maybe) signaling that those files need to be transcribed (if simply writing them to the bucket isn't enough)
- picking up a workflow step signaling that the transcription output has been placed in an S3 bucket
- updating the cocina appropriately and accessioning the output files

Currently, there is placeholder workflow step code for starting the workflow, ending it, and generating speech-to-text output (this last part will very likely be broken into the multiple steps describe above).

**Comment by peetucket** [comment]
Closed by #1342
