### ISSUE TITLE
Adjust logic for files available for speech to text extraction

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1346]
This PR https://github.com/sul-dlss/common-accessioning/pull/1342/files adds a new STT robots, and includes some logic that lets the robots decide which types of objects and which types of files are available for speech to text, so we know which files to send to Whisper.  

We should ensure those configured options make sense.  The file is `lib/dor/text_extraction/speech_to_text.rb`

~~Blocked by https://github.com/sul-dlss/common-accessioning/pull/1342 (until that is merged)~~

We currently check for mimetype, but we need to also other check to only select files that are:

* shelved (other files can be ignored regardless of mimetype).
* we need to adjust the mimetypes that are selected as well to only be audio/mp4 and video/mp4
* we need to ensure the resource types match (e.g. "video", "audio", "file" maybe?) confirm with Andrew

**Comment by andrewjbtw** [comment]
Waiting on discussion over which files to choose.
