### ISSUE TITLE
Investigate/add the ability to stream files to S3 from preservation

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1352]
See sul-dlss/common-accessioning#1345

We will be likely fetching files from preservation and send directly to S3 (the analogy from OCR is fetching from preservation and storing to local mount).

Can we stream directly to S3 from preservation in the same way so we can do this in one robot step?  Let's find out.

**Comment by jmartin-sul** [comment]
looking at the documentation link that came up from a search i did this morning but hadn't followed up on...

seems _maybe_ possible?  [the "Streaming Uploads" section on this page](https://docs.aws.amazon.com/sdk-for-ruby/v1/api/AWS/S3/S3Object.html) (sorry, I couldn't find a link directly to the section) says you can call `S3Object#write` with a block:

```ruby
You may also stream uploads to S3 using a block:

obj.write do |buffer, bytes|
  # writing fewer than the requested number of bytes to the buffer
  # will cause write to stop yielding to the block
end
```

...but then [the API documentation specifically for the `#write` method](https://docs.aws.amazon.com/sdk-for-ruby/v1/api/AWS/S3/S3Object.html#write-instance_method) seems to make no mention of that?

anyway, seems like something to try.


another possibility: that `#write` documentation says that it'll take "IO objects (must respond to #read and #eof?)".

**Comment by jmartin-sul** [comment]
looks like there's also `Object#upload_stream`: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_stream-instance_method (found via https://github.com/aws/aws-sdk-ruby/issues/2364)
