### ISSUE TITLE
`speechToTextWF`: notify speech_to_text_generation_service that there is content to be STTed

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#1356]
discussion and prototyping on https://github.com/sul-dlss/speech-to-text/pull/9 led to us settling on sending messages via SQS, which our cloud speech-to-text container will watch.

this is the push-to-cloud-for-extraction counterpart of https://github.com/sul-dlss/common-accessioning/issues/1358

part of https://github.com/sul-dlss/common-accessioning/issues/1363

**Comment by peetucket** [comment]
Will do this in the existing stt_create robot to keep it as a discrete step from the fetch-files step

We can then either (1) leave the step as running and then have a daemon or other process come back later to mark it as complete or (2) complete the step immediately and a new "waiting-for-stt" type step that will be marked complete when the process is done.

**Comment by jmartin-sul** [comment]
things we considered but decided against:
- make a call to a REST API that we write that invokes speech_to_text_generation_service
- having the speech-to-text service watch an S3 bucket for incoming files to extract text from

see https://github.com/sul-dlss/speech-to-text/issues/3#issuecomment-2368453338
