### ISSUE TITLE
`speechToTextWF` `update-cocina`: update cocina structural to reference files generated by speech_to_text_generation_service

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#1361]
for now, blocked by the implementation of preceding steps in `speechToTextWF`, but we could probably parallelize this with work on the preceding steps, if we wanted.  we might be able to work off of the `ocrWF` equivalent as an example?

this is the `speechToTextWF` equivalent of [`ocrWF` `update-cocina`](https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/ocr/update_cocina.rb)

stub code in the `speechToTextWF`: https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/speech_to_text/update_cocina.rb

part of https://github.com/sul-dlss/common-accessioning/issues/1363

**Comment by peetucket** [comment]
Note: at the moment, this step is implemented using the exact same algorithm used by the ocr update-cocina step, which means it picks up new files in the workspace generated by Whisper, finds resources with base filenames that match, and then adds them to the resource.

We still need to consider:
1. which files get roles (e.g. transcription)
2. if all files should be added or only of a certain mimetype

**Comment by peetucket** [comment]
**Roles:**

".vtt" = "caption"
".txt" = transcription?

**Comment by jmartin-sul** [comment]
captions confirmed to display correctly

**Comment by jmartin-sul** [comment]
we think is done.  if we find bugs in the cocina generation, we can ticket them separately.
