### ISSUE TITLE
`speechToTextWF` `end-stt`: hand off to `accessionWF`

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#1362]
blocked by implementation of the rest of `speechToTextWF`?  since that would be necessary for end-to-end testing.  thought there is probably a way to test this by manually staging files and cocina, should we want to parallelize this with other `speechToTextWF` development.

this ticket may just involve confirming that https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/speech_to_text/end_stt.rb is sufficient.  the implementation work may essentially be done?

note that the (currently functional) `ocrWF` equivalent looks the same as what's already there for `speechToTestWF`.  all of the differentiating implementation between `ocrWF` and `speechToTextWF` probably happens in steps earlier in `speechToTextWF`?

part of https://github.com/sul-dlss/common-accessioning/issues/1363

**Comment by peetucket** [comment]
I would argue this specific ticket is done and we can close this ticket, as the implementation will close the version, which will start accessioning (same as OCR).

Of course, we can't exercise it for now, but we can leave that to a separate end-to-end test ticket.

**Comment by peetucket** [comment]
This works as expected, as demonstrated in this object that went through the integration test: https://argo-qa.stanford.edu/view/druid:ds827kg5729
