### ISSUE TITLE
No role applied to Whisper-generated files on QA

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#1414]
I recently accessioned three items in QA using the automated pipeline. Whisper produced caption files but the expected role of "caption" was not applied to any of them when the caption files were accessioned.

The three items can be found in [this search](https://argo-qa.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Bengali+media).

**Comment by peetucket** [comment]
I think it's simply because the code that does this was not deployed to QA since the merge to add them happened after dependency updates were deployed to QA and then main was never re-deployed.

**Comment by peetucket** [comment]
I confirmed the latest code was not out there.  I have deployed main to QA to make sure it's out there.  I'll run the integration test now in QA.  Not sure if we want to re-run one of these objects just to be doubly sure?  Should be able to just open the object and kick off speech to text again with the "Text extraction" button.

**Comment by peetucket** [comment]
Deployment issue
