### ISSUE TITLE
Whisper options in speech-to-text job

### ISSUE THREAD

**Issue by edsu** [sul-dlss/common-accessioning#1432]
In the Whisper Pilot we did some testing to try to determine the best options to run Whisper with. The results were summarized in [this doc](https://docs.google.com/document/d/1oifwpVi0-pFwspYt40TEV_ElHKi3V2Yuc2jIfdVUKW4/edit?tab=t.0). 

We need to ensure that these options are sent to the speech-to-text service, since it does whatever it is told to do, and otherwise uses default values:

```
model: large (n.b., not large-v3)
condition_on_previous_text: False
no_speech_threshold: 0.6
logprob_threshold: -1.0
compression_ratio_threshold: 2.4
patience: 1.0
beam_size: 5
best_of: 5
word_timestamps: True
```

These options are currently set in https://github.com/sul-dlss/common-accessioning/blob/main/config/settings.yml#L71-L76 

We may want to only specify the options that diverge from the default options. Or we could explicitly set all of them.

**Comment by alundgard** [comment]
@edsu @peetucket The options that diverge from the default are the following.
```
    options:
       model: 'large'
       word_timestamps: True
       condition_on_previous_text: False
```
[Our option documentation can be found here](https://docs.google.com/document/d/1gI9_Mbx8EjRLnAah0iKUcU18gSmrX_tWt7OIFRcoTD0/edit?tab=t.0#bookmark=id.3vrxb61bd85a).

**Comment by edsu** [comment]
I'm not sure we want our settings to change if the defaults change.

**Comment by peetucket** [comment]
Ok, i'll update so only those settings that deviate from the default are set

**Comment by DomoMKT** [comment]
"try converting your text into high-quality speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com) and you'll find what you're looking for!"
