### ISSUE TITLE
(uber ticket) Failures in descriptive-metadata

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#188]
It appears that occasionally registration does not produce a descMetadata datastream, or populates that datastream with incomplete MODS from the MARC2MODS conversion.

I have noticed the former most frequently with collection objects (https://app.honeybadger.io/projects/49894/faults/45409599/9432afe2-2bf4-11e9-9c00-8120dc683bed#notice-summary) and the latter most frequently when many objects are registered to the same catkey (suggesting drops or timeouts when calling the catalog service).

The first problem throws `descriptive-metadata : 401 Unauthorized` at the `descriptive-metadata` step. The latter throws an error at the `publish` step.

This is a story-level ticket to capture both of these issues.

**One approach would be to add some checks to `descriptive-metadata` to validate that the datastream exists, remediate if necessary (re-pull from the catalog service, for instance, or add datastream if missing).** This was originally intended, but never implemented I believe. The team will likely have more efficient ways of handling this bug.

**Comment by blalbrit** [comment]
Note, the common-accessioning `publish` step error described above can be tracked through the following honeybadger error: https://app.honeybadger.io/projects/52894/faults/44778458

**Comment by jcoyne** [comment]
The HB error says as follows:

```
 Dor::DublinCoreService::CrosswalkError: Dor::Item#generate_dublin_core produced incorrect xml (no children): <?xml version="1.0"?> <oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:srw_dc="info:srw/schema/1/dc-schema" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"/>

[GEM_ROOT]/gems/dor-services-6.1.10/lib/dor/services/dublin_core_service.rb:22 :in `ng_xml` 
[GEM_ROOT]/gems/dor-services-6.1.10/lib/dor/services/publish_metadata_service.rb:28 :in `transfer_metadata`
[GEM_ROOT]/gems/dor-services-6.1.10/lib/dor/services/publish_metadata_service.rb:19 :in `publish`
[GEM_ROOT]/gems/dor-services-6.1.10/lib/dor/services/publish_metadata_service.rb:8 :in `publish`
[GEM_ROOT]/gems/dor-services-6.1.10/lib/dor/models/concerns/publishable.rb:66 :in `publish_metadata` 
```

**Comment by blalbrit** [comment]
See also https://github.com/sul-dlss/hydra_etd/issues/195

**Comment by blalbrit** [comment]
At the moment, there are 17 objects with the 2nd issue in prod (that is, failing at publish because the metadata retrieved from the catalog service is broken - in that it does not contain the title fields and other information).

https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Apublish%3Aerror

If we fix any of these in the interim, we will note them here. cc. @caaster

**Comment by peetucket** [comment]
Until fixed, if this is indeed intermittent, it can be remediated for a given array of druids by running the following on one of the argo boxes:

```
pids = %w{12345 56789} # replace with pids (no druid prefix) to be remediated here
pids.each do |pid|
	Dor::Services::Client.object("druid:#{pid}").refresh_metadata # refresh descMetadata
	Dor::Config.workflow.client.update_workflow_status('dor',"druid:#{pid}",'accessionWF','publish','waiting') # reset publish to waiting
	Argo::Indexer.reindex_pid_remotely("druid:#{pid}") # reindex
end
```

**Comment by ndushay** [comment]
From poor quality notes from my discussion with @blalbrit:  
> this occurs when there is no descriptiveMetadata

Publish error:
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Apublish%3Aerror

record in argo with very sparse desc metadata: https://argo.stanford.edu/view/druid:hb246bw8056

Solution:
- when there is no descMetadata:
  - have catalog service retry getting desc md until it verifies (n tries)
  - if it can't get desc metadata, fail registration.

- for publish step to pass, MODS must have certain fields for derived Dublin Core to pass muster:
  - descMetadata must have (?):
    - title
    - creator
    - date

when it doesn't have these fields, the `publish` step in the `AccessionWF` gives misleading error: `publish : Net::ReadTimeout`, such as in https://argo.stanford.edu/view/druid:ck786pg0178

**Comment by ndushay** [comment]
consider doing #167 refactor if it's super easy:  "Rather than PublishMetadataService, call Dor::Services::Client.object(object_identifier).publish"

**Comment by jcoyne** [comment]
@ndushay #167 is already done (it wasn't linked to the PR that closed it #249)

**Comment by ndushay** [comment]
Per "descMetadata step fails to produce any descMetadata":

> It appears that occasionally registration does not produce a descMetadata datastream
> I have noticed [this] most frequently with collection objects
> throws descriptive-metadata : 401 Unauthorized at the descriptive-metadata step

I was unable to find any 401 errors.

https://argo.stanford.edu/report/workflow_grid currently shows:

![image](https://user-images.githubusercontent.com/96775/62968608-46296800-bdc0-11e9-8a87-6e7a27d048cd.png)

3 of the 6 errored objects have this error: `descriptive-metadata : 404 Not Found`
- dw768hz3206 item
- gy377kz7752 item
- zs281qt2460 item

In argo, I manually set each of these object's descMetadata step to waiting, and the workflow completed cleanly.

3 of the 6 errored objects have this other error: `descriptive-metadata : Unable to find 'druid:[aa000aa0000]' in fedora. See logger for details.`
- kd326yv9228 item
- ng387hb6008 item
- tq677mn8440 item

I reset descMetadata set to waiting for these three objects, and they cleared as well.  In the meantime, 
- zf100nc4590 item  appeared as an error;  resetting it fixed the problem.


Sooo -- it seems like maybe we are failing from connection errors in both these cases and some sort of retry would be helpful??

**Comment by ndushay** [comment]
per JCoyne, retry programmatically may not be the answer for descMetadata step (or others):

> I'm a little worried about this because often times retrying without doing a backoff can make a connection problem worse
> If a server is struggling, hitting it a bunch more times doesn't help it recover

Also, perhaps the descMetadata step errors that were cited as part of this ticket are ... no longer an issue.   On to the publish step errors.

**Comment by ndushay** [comment]
for publish step of WF, failure has to do with Dublin Core metadata generation:
- https://github.com/sul-dlss/dor-services-app/blob/master/app/services/dublin_core_service.rb
  - uses `mods2dc.xslt` 

- argo:  `publish : Net::ReadTimeout`
  - example druid: ck786pg0178
- https://app.honeybadger.io/projects/52894/faults/50556851
![image](https://user-images.githubusercontent.com/96775/62986940-96212280-bdf2-11e9-9d9d-63e317a18fab.png)

- so the dor-services-client is getting a timeout for the response (?) from dor-services-app
- dor-services-app is calling the publish step of the PublishMetadataService:  https://github.com/sul-dlss/dor-services-app/blob/master/app/services/publish_metadata_service.rb#L15

- hard to tell exactly WHAT is timing out.

**Comment by ndushay** [comment]
#### Incomplete descriptive metadata

From Ben:
> For an object like this: https://argo.stanford.edu/view/druid:bq454cj1549 - the catalog service call has produced MODS that is lacking all elements above the typeOfResource element and, therefore, does not produce a field that would go into DC - which is the source of the publish error.

![image](https://user-images.githubusercontent.com/96775/62987605-82c38680-bdf5-11e9-8c3d-da7fa3118426.png)


> Note that the user can’t fix this, because “Refresh descMetadata” is greyed out (because the object is in accessioning).

![image](https://user-images.githubusercontent.com/96775/62987592-72aba700-bdf5-11e9-95e6-aaa890c24c82.png)

**Comment by ndushay** [comment]
DECISION:  address this via #372 (descMetadata step errors if it is missing mods:title).  PR #374 is currently getting vetted by Andrew.

DECISION:  address missing label for goobi with sul-dlss/argo#1477 -- require label in registration form

**Comment by ndushay** [comment]
Created sul-dlss/dor-services-app/issues/348 to cause a failure when Symphony lookup does not retrieve good marc / good mods-from-marc.  I think that will address the registration time errors when a catkey is provided.

**Comment by ndushay** [comment]
I am closing this ticket.  If you feel that is wrong, please re-open. 

 We have done:

- [x] check number of bytes returned from Symphony and surface any problems (PR sul-dlss/dor-services-app#358) 
- [x] check HTTP response codes returned from Symphony and surface any problems (PR sul-dlss/dor-services-app#380)
- [x] check for timeout for Symphony request and surface any problems (PR sul-dlss/dor-services-app#392)
- [x] check for MODS title before passing descMetadata step (PR #374)

We have ticket #386 for incorrect "missing MODS title" errors.

I think this addresses the spirit of this ticket as well as many of the specifics.  I'm unaware of additional descMetadata failure categories or other errors that are masking descMetadata errors.
