### ISSUE TITLE
Technical metadata error: Bad request 400

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#240]
https://app.honeybadger.io/projects/52894/faults/48389061#notice-summary for full info.

Also see: https://argo.stanford.edu/view/druid:yt299hq5746

**Comment by jcoyne** [comment]
In this case, the robot is calling dor-services-app, which is proxying to sdr-services-app, where this error originated: https://app.honeybadger.io/projects/52898/faults/38275683

```
Moab::InvalidMetadataException: File node having id='21-B-69.TIF' is missing size,md5,sha1 ...
```

**Comment by blalbrit** [comment]
For some reason, this object came through without its hydrus-generated contentMetadata. Even re-setting accessioning didn't repull the contentMD.

I manually copied the Hydrus contentMD into the contentMD datastream in DOR and that did the trick.
