### ISSUE TITLE
Availability of profiles for tiff/jpg to jp2 conversion

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#241]
See: 

tiff convert command failed: MAGICK_TEMPORARY_PATH=/imtmp convert -quiet -compress none -type TrueColor -profile /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/assembly-image-1.7.4/profiles/AdobeRGB1998.icc -profile /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/assembly-image-1.7.4/profiles/sRGBIEC6196621.icc '/dor/assembly/cv/420/xc/7404/cv420xc7404/content/cv420xc7404_0001.tif[0]' '/imtmp/assembly-image20190417-29927-135qte0.tif' with result TIFFWriteDirectoryTagData: IO error writing tag data. convert: Write error at scanline 18037. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/560. convert: IO error writing tag data. `TIFFWriteDirectoryTagData' @ error/tiff.c/TIFFErrors/560.
--

Looking in /imtmp, the list of available profiles differs from the old robots machines. @calavano may be able to specify further

**Comment by jcoyne** [comment]
@tallenaz is this something that should be in puppet?

**Comment by tallenaz** [comment]
Possibly. To be sure, I'd want to know more about those profiles, and how they were put in place on the sul-robots.

**Comment by calavano** [comment]
The most common profiles would normally be kept in the git repo for aseembly-image, e.g. https://github.com/sul-dlss/assembly-image/tree/master/profiles

The gem was set up to extract the profile of the source tiff to the temp dir if it wasn't found with the gem. We shouldn't need to go out of our way to include all the different ICC profiles as it would just be extracted from the source tiff.

**Comment by tallenaz** [comment]
Since the two profiles in the error are in the gem, and I see that the common-accessioning version of imageMagick is behind the sul-robots version, I'll look into upgrading it and we'll see if that gets us past the error.

**Comment by tallenaz** [comment]
I've upgraded ImageMagick to 6.9.10.40-1 on stage. `yum` wouldn't install the same version as sul-robots, which is at  6.9.5.10-1, because 6.9.10 supersedes. @blalbrit can we test whether the upgrade fixes this issue in stage?

**Comment by tallenaz** [comment]
This could be a corrupted tiff, but it's not an issue with the profiles.

**Comment by mtrottstanford** [comment]
Hi all, I wanted to provide some context:
We're seeing this jp2 creation issue when accessioning content via Goobi that was, prior to being uploaded to Goobi, LZW compressed and converted to Adobe RGB 1998 using an automated script @calavano  created for us.  So far it has impacted 277 total maps that we've tried to accession (around 150 GB of data).  We also have 657 maps (estimated 350 GB of data) that are on hold until a fix is found for this issue. I don't feel like I'd be in a good position to do the amount of remediation required if I were to send all of those through accessioning and all or a majority of them encountered these jp2 errors. 
Is there anything I can do to help move this along? Would you like me to attempt accessioning on a few more items to test? 
cc: @dinahhandel @dfuzzell

**Comment by tallenaz** [comment]
@calavano was able to run some of the problematic files successfully with imagemagick7 and libtiff4. It doesn't look like the tiffs themselves are bad. We can look into updating to imagemagick7, etc. on the common-accessioning-prod machines, which are ol7.

**Comment by tallenaz** [comment]
We upgraded to ImageMagick7 on the common-accessioning-prod machines and druid:cv420xc7404 has completed the jp2-create step.

**Comment by tallenaz** [comment]
After running the rest of the problem objects in jp2-create, there are currently 14 in an error state, and none of them exhibit the `IO error writing tag data`.
