### ISSUE TITLE
release-members for some collection items failing

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#274]
Copying from https://github.com/sul-dlss-deprecated/item-release/issues/99 since item-release repo is now deprecated.

According to @hannahfrost: 
> This bug is resurfacing now, in this case here: https://argo.stanford.edu/view/druid:yp581yt0894

**Comment by jcoyne** [comment]
Here's the backtrace: https://app.honeybadger.io/projects/52894/faults/48481790
