### ISSUE TITLE
Transfer etd MARC records to Symphony using NFS

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#276]
Currently the system is configured for AFS, but AFS is being retired and is not installed on the new worker machines.

See: https://github.com/sul-dlss/common-accessioning/blob/master/bin/run_marc_builder.sh#L16-L18

https://github.com/sul-dlss/shared_configs/blob/common-accessioning-prod/config/environments/production.rb#L139

**Comment by tallenaz** [comment]
@jcoyne common-accessioning is set up with NFS mount points to symphony at `/etd`
