### ISSUE TITLE
Error exporting new object version to bag: Signature inconsistent between inventory and file for ...

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#310]
## Backtrace

    line 39 of [PROJECT_ROOT]/lib/sdr_ingest_service.rb: rescue in transfer
    line 8 of [PROJECT_ROOT]/lib/sdr_ingest_service.rb: transfer
    line 13 of [PROJECT_ROOT]/robots/dor_repo/accession/sdr_ingest_transfer.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/49465672)

**Comment by jcoyne** [comment]
@blalbrit said:
> we’ve seen this before and @gwillard and @azanella may know more. I think this crops up when media is either run through the accessioning process using the “symlink” style (something going awry in checksum generation for symlinked objects) or in the ways checksums are being produced in pre-assembly vs. in the sdr-ingest-transfer step. @gwillard - any thoughts on this object?

**Comment by peetucket** [comment]
Triggered at this line: https://github.com/sul-dlss/common-accessioning/blob/master/lib/sdr_ingest_service.rb#L14 when we run `verify_version_metadata`

**Comment by peetucket** [comment]
So, for example https://argo.stanford.edu/view/druid:xm078yz7382, v3 already exists on disk in the preservation system when the robot runs, and it is complaining because we are trying to send it v3.  SDR ingest is expecting that you'll be sending it v4 to preserve.

The version IDs are determined
- on the DOR side by inspecting the `versionMetadata` datastream and looking for the last node (not necessarily the biggest number, though it is in this case)
- on the preservation side by looking at the biggest `vXXX` folder on the preservation disk

For this example object above, we have 3 in both cases.

**Comment by peetucket** [comment]
Oddly enough for that `https://argo.stanford.edu/view/druid:xm078yz7382,` object, the `sdr-ingest-transfer` step does not appear to have been run prior to the error (which occurred on July 10).  And also oddly the `v0003` folder on the preservation disk is timestamped for Jun 7, but there is not an `sdr-ingest-transfer` step in the workflow XML that appears to have run then, so I'm not sure how that `v0003` folder got there.

**Comment by peetucket** [comment]
One possible path for this particular item:

- user registers an item in argo without any initial workflows, and does not accession anything yet
- user later versions the item to add the GoobiWF to get the item showing up in Goobi, a version gets preserved
- user later goes into Goobi to add content and uses the export feature of Goobi
- the export feature in Goobi is not aware of versioning -- it puts content into the /dor mount and then kicks off `assemblyWF`, which then kicks off `accessionWF`, which then attempts to preserve the same version of the object again, throwing the mismatch error

Remediation of the object involves updating the `versionMetadata` datastream in DOR to add a new version stanza, mimicking the opening of a new version that should have happened before `assemblyWF` was kicked off.

Better solution is to have an alternate export process from Goobi that does not kick off
`assemblyWF` automatically. The user would use this alternative export process, then head back to Argo to version an item and add the `assemblyWF` workflow manually.

**Comment by peetucket** [comment]
Note that manual remediation leaves the items with an "unknown status", because there are no milestones/workflow steps in the Workflow database with the manually bumped version number in the versionMetadata stream.  I believe this would heal itself if you were to re-version the object.

**Comment by jcoyne** [comment]
Here is one instance I'm investigating: https://argo.stanford.edu/view/druid:bb461xx1037  where there is a version 3 in preservation:
```
drwxrwxr-x 4 sdr2service sdr2service 4096 Mar 25  2019 v0003
```

But there is no corresponding record of this in DOR.

**Comment by jcoyne** [comment]
@andrewjbtw We haven't seen this in awhile. Can we close it?

**Comment by andrewjbtw** [comment]
This pre-dates me and at this point I'm not sure what it's referring to because different parts of the system have changed over time. I think we can just close it since there's no way at this point to connect it to a current issue with any certainty.

**Comment by jcoyne** [comment]
@andrewjbtw this is the checksum mismatch stuff we wrestled with in the fall.

**Comment by andrewjbtw** [comment]
Last fall's issues had different tickets: #439 #453 

Solving those could very well have solved this.
