### ISSUE TITLE
Simplify number of queues

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#318]
We think that by passing the class (like activejob) or by passing the workflow step id to the job we can reduce the number of queues from dozens to 3 (high, default, low) per workflow.

**Comment by ndushay** [comment]
Is this still a valid ticket?  Should it be referenced in "workflow-level queues" work?

**Comment by jcoyne** [comment]
It is still a valid ticket and it would be completely separate from the workflow-level queues

**Comment by jcoyne** [comment]
Fixed by #384
