### ISSUE TITLE
Switch to sidekiq (background to #902)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#319]
Some of the department projects already use Sidekiq. The department has a Sidekiq pro contract and Resque is only receiving minimal maintenance.  Additionally Sidekiq is threaded so we can run more processes with less memory.

**Comment by jmartin-sul** [comment]
i'll just point out the sidekiq thread safety issue:  https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#threading

> Threading
> 
> Sidekiq is multithreaded so your Workers must be thread-safe.
> Use only thread-safe libraries!
> 
> Most popular Rubygems are thread-safe in my experience. A few exceptions to this rule...
> Not thread safe gems:
> 
>     right_aws
>     aws-s3
>     basecamp
>     therubyracer #270
> 
> Some gems can be troublesome:
> 
>     typhoeus has a history of crashing a lot
>     pg (the postgres driver, make sure PG::Connection.isthreadsafe returns true)
>     RMagick (see #338, try mini_magick instead)
>     libxml-ruby (see #1174)
>     aws-sdk v1 (use AWS.eager_autoload! during initialization)
>     sidekiq-statistic - has a major memory leak
>     mail (use Mail.eager_autoload! per https://github.com/mikel/mail/issues/912)
> 

i don't know this codebase, so no idea whether it'd be an issue here (and i figure there's a good chance you're aware of this anyway, but also figured better safe than sorry).

**Comment by jcoyne** [comment]
@jmartin-sul yes, I don't think that'll be a problem.

**Comment by ndushay** [comment]
sidekiq, or resque-pool??

**Comment by mjgiarlo** [comment]
I have a preference for Sidekiq, because: 

1. it's better supported and maintained than resque-pool;
1. I've had positive experiences with it compared to r-p;
1. Sidekiq has a for-fee "pro" version that provides compelling features if we want to upgrade

I've also used r-p and either is probably fine. FWIW, I haven't seen any problems w/ Sidekiq's threading in codebases in which I've used it, but it's good to keep this in mind when analyzing the options.

**Comment by jmartin-sul** [comment]
if thread-safety isn't an issue, i have no objection to sidekiq.  i know we've used resque-pool a bunch in the last couple years on the infrastructure team.  but we've used sidekiq in the past also, and access has used it more heavily, so we have experience with it in the department.  and for at least a couple of the projects we used reqeue-pool on in recent years, we had well-founded thread-safety concerns (use of the aws sdk gem in pres cat, some class variable caching ported to pres robots from its predecessor codebase).

**Comment by jcoyne** [comment]
@jmartin-sul the thread safety issue with aws sdk was fixed in version 2.  Of course class variable caching would be a thread safety issue, but preservation robots is not part of this codebase.

**Comment by jmartin-sul** [comment]
@jcoyne, thanks, good to know on aws SDK!  and i only mentioned pres robots as an example of something that might not play well with sidekiq, not as a blocker to using it in common-accessioning.

**Comment by andrewjbtw** [comment]
I think this can be closed now? I'd forgotten we had this ticket.

**Comment by jmartin-sul** [comment]
yup, closing! 🎉
