### ISSUE TITLE
Web archiving items aren't being shelved

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#322]
## Backtrace

    line 105 of [PROJECT_ROOT]/lib/digital_stacks_service.rb: copy_file
    line 88 of [PROJECT_ROOT]/lib/digital_stacks_service.rb: block (2 levels) in shelve_to_stacks
    line 83 of [PROJECT_ROOT]/lib/digital_stacks_service.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/49707504)

Ops needs to mount a volume for us: https://github.com/sul-dlss/operations-tasks/issues/1891

**Comment by tallenaz** [comment]
The web archiving volumes are mounted by https://github.com/sul-dlss/puppet/pull/4160
