### ISSUE TITLE
dissemination cleanup should use the dor-service-app endpoint

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#333]
See https://github.com/sul-dlss/dor-services-app/pull/300

Also remove CleanupResetService as it moved to dor-services-app
Then we can move Dor::CleanupService from dor-services to dor-services-app

**Comment by peetucket** [comment]
This appears to be done?  The dissemination cleanup step in common-accessioning is hitting a `dor-services-client` defined endpoint.  See https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/dissemination/cleanup.rb

**Comment by peetucket** [comment]
I also see a CleanupService in dor-services-app so perhaps that part is done too? https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cleanup_service.rb

**Comment by jcoyne** [comment]
Yes, this appears to be complete.
