### ISSUE TITLE
/dor mount not getting cleaned up

### ISSUE THREAD

**Issue by kamchan** [sul-dlss/common-accessioning#342]
Is this a dup of #321 ?  Is the fix similar?  Can we fix #321 at the same time, please?

<hr />

The /dor mount is mounted on various servers.  It is about 21TB and nagios warned that it was getting full at 80%.  Normally content is automatically trimmed from that mount (particularly `/dor/export` and `/dor/workspace`).  It looks like that process is not working correctly.

**Comment by peetucket** [comment]
Did some spot checking of druids in the /dor/export folder and found at least one that is in error state, explaining why its not cleared yet...i manually re-ran the `disseminationWF:cleanup` step on a couple others that were complete and it did clear them, so the code appears to be working, so not sure why robot step was set to complete when it wasn't deleted

**Comment by peetucket** [comment]
e.g. `./bin/run_robot dor:disseminationWF:cleanup -e production -d druid:zz998dj6963`

**Comment by peetucket** [comment]
not entirely clear what `accessionWF:reset-workspace` does as opposed to `disseminationWF:cleanup`, needs some investigation perhaps

**Comment by peetucket** [comment]
Looks like `accessionWF:reset-workspace` moves the `/dor/workspace` druid tree folder to an archived folder and it worked when I re-ran for `druid:zz998dj6963`

**Comment by peetucket** [comment]
Still not sure what clears out the archive folder though (e.g. `/dor/workspace/zz/998/dj/6963/zz998dj6963_v2`)

**Comment by peetucket** [comment]
see also #321

**Comment by ndushay** [comment]
Is this related?  https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=disseminationWF%3Acleanup%3Aerror.  that shows a record that errored on the disseminationWF step ...

![image](https://user-images.githubusercontent.com/96775/61745964-81032780-ad4f-11e9-9f9c-c734ab763659.png)

**Comment by peetucket** [comment]
Possible.  I think we need to look at what the cleanup step does and enumerate its functions.  There may be multiple spots that need cleaning (/dor/workspace and /dor/export) and I'm not sure if those occur in the cleanup step or in two separate steps.

**Comment by ndushay** [comment]
Is this related to #321 ?  Is the fix similar?

**Comment by peetucket** [comment]
As noted above, this is sufficiently similar if not the same as #321, closing this so that we can track everything in a single spot.
