### ISSUE TITLE
Update logging information for combined robots and separate by robot

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#345]
It appears that on each of the `common-accessioning-XXX` boxes, the `#{ENVIRNONMENT}.log` file and each individual robot named log file is no longer being updated after April 11, 2019.  Instead, information is getting logged in `resque-pool.stdout.log` and `resque-pool.sterr.log` in a combined way for all robots.

We need to:

- [x] confirm if this is actually true
- [ ] setup log rotation for this files (https://github.com/sul-dlss/operations-tasks/issues/1936) so it doesn't get so huge and so it is backed up
- [x] update DevOpsDocs as needed to reflect this
- [ ] if possible write to separate logs by robot instead of by robot suite
- [ ] ensure the log file includes enough information to debug -- currently it appears to log when a druid was completed, but not which step was being run

**Comment by ndushay** [comment]
the combined log now indicates the workflow by name ... is that sufficient?

**Comment by peetucket** [comment]
was still helpful separated out by robot, but grepping works too ... not sure what others think

**Comment by jcoyne** [comment]
I think grepping is fine.

**Comment by mjgiarlo** [comment]
I'm :100: OK with grepping as well.

**Comment by ndushay** [comment]
I'm closing this ticket.  If that's undesired, please reopen.
