### ISSUE TITLE
embargo-release cron raises Zeitwerk::Error

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/common-accessioning#349]
Running this command locally: https://github.com/sul-dlss/common-accessioning/blob/master/config/schedule.rb#L6-L9

Throws the following error: https://app.honeybadger.io/projects/52894/faults/51926096#comment_9179659

Though running https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/accession/embargo_release.rb#L78 from the console does get the embargo release process going

**Comment by peetucket** [comment]
Looks suspiciously like this problem previous fixed by @jcoyne 	: https://github.com/fxn/zeitwerk/issues/53

**Comment by peetucket** [comment]
and our PR that fixed it in dor-services-client: https://github.com/sul-dlss/dor-services-client/pull/65/files
