### ISSUE TITLE
release tag is not getting updated on purl

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/common-accessioning#355]
This collection was released to SearchWorks: druid:mw020xq9940

But PURL still thinks it is not released: https://purl.stanford.edu/mw020xq9940.xml

`<release to="Searchworks">false</release>`

**Comment by peetucket** [comment]
What we've seen so far:

1. The releaseWF workflow was correctly added to the collection, and ran successfully.
(collection items in Argo: https://argo.stanford.edu/catalog?f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=Stanford+University%2C+School+of+Earth+Sciences%2C+Oral+history+interviews%2C+1983-1999)
2. The release-members step then picked up the 10 actually accessioned items and added the releaseWF workflow.  (accessioned collection items in Argo: https://argo.stanford.edu/catalog?f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=Stanford+University%2C+School+of+Earth+Sciences%2C+Oral+history+interviews%2C+1983-1999&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned)
3. The items themselves are released to Searchworks (e.g. https://searchworks.stanford.edu/view/bb488wg4391) but the collection itself is not (e.g. https://searchworks.stanford.edu/view/mw020xq9940)

**Comment by peetucket** [comment]
The releaseWF workflow users dor-fetcher-service to get the members of the collection: https://github.com/sul-dlss/common-accessioning/blob/master/lib/dor/release/item.rb#L22-L26

This method only returns the accessioned items, which probably makes sense.

**Comment by peetucket** [comment]
The object has these tags in `identityMetadata`: 

```
<release to="Searchworks" what="self" when="2016-11-16T23:04:26Z" who="blalbrit">true</release>
  <release to="Searchworks" what="self" when="2017-07-11T20:28:50Z" who="arcadia">false</release>
  <sourceId source="sul">SC1105</sourceId>
  <release to="Searchworks" what="collection" when="2017-08-23T22:37:14Z" who="dhartwig">true</release>
  <release to="Searchworks" what="collection" when="2019-06-28T21:32:22Z" who="dhartwig">true</release>
  <release to="Searchworks" what="collection" when="2019-07-07T19:50:12Z" who="dhartwig">true</release>
  <release to="Searchworks" what="collection" when="2019-07-09T15:44:21Z" who="dhartwig">true</release>
  <release to="Searchworks" what="collection" when="2019-07-15T23:10:47Z" who="dhartwig">true</release>
  <release to="Searchworks" what="collection" when="2019-07-16T19:26:15Z" who="hfrost">true</release>
```

There are two `what="self"` tags, the latest one is set to `false`.

This line in `dor-services` is then picking up the false as the latest release: 

https://github.com/sul-dlss/dor-services/blob/7-2-stable/lib/dor/services/release_tag_service.rb#L25

and this code in `dor-services-app` that publishes the XML picks it up and adds it to the public xml:

https://github.com/sul-dlss/dor-services-app/blob/master/app/services/public_xml_service.rb#L39-L50

**Comment by peetucket** [comment]
we could ditch the "false" tag

**Comment by blalbrit** [comment]
Yep - in the past we've just cleaned up the tagging to get over this kind of hump. The self vs. collection tags have been problematic.

**Comment by peetucket** [comment]
Not quite sure I understand the distinction between "self" and "collection" and if both are needed in cases like this (and/or how they would get added, presumably via Argo in some way).  So in this case, we would delete the the "false" tag manually, and re-publish the collection?

**Comment by peetucket** [comment]
OK, @aaron-collier 	remediated the tags by switching the "false" and "true" and re-published, and PURL looks ok, as does the record in purl-fetcher, which feeds the API that searchworks-indexer uses .... so I think this should correct this should cause it to get indexed into searchworks...

though, that collection already seems to be there via a catkey record (and linked to from the PURL): https://searchworks.stanford.edu/view/4755369 ... so not sure if the searchworks indexer will merge the records?

**Comment by hannahfrost** [comment]
Thanks, @peetucket and @aaron-collier. The two records should become merged automatically, yes.

**Comment by peetucket** [comment]
Just curious, how do we know if that worked?  Will there be a searchworks record with the druid as well as the catkey?

**Comment by hannahfrost** [comment]
The record with the catkey will display stuff about the associated digital collection at the top of the page, as seen here: https://searchworks.stanford.edu/view/12712987

**Comment by blalbrit** [comment]
@peetucket - for more info on self and collection release, why you would do that, and what the expectations are around time and success, please see: https://consul.stanford.edu/display/DLSSDOCS/Managing+the+Release+of+SDR+Resources+to+SearchWorks - we can update that documentation if the situation on the ground has changed over time.

**Comment by hannahfrost** [comment]
Fixed. The solution to this problem is now documented here: https://consul.stanford.edu/display/DLSSDOCS/Managing+the+Release+of+SDR+Resources+to+SearchWorks
