### ISSUE TITLE
re-export from goobi (?) should correctly deal with object versioning

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#361]
From sul-dlss/argo/issues/1147:

@peetucket says

    Possibly also an issue when a user is using Goobi (i.e not just pre-assembly) ... and they re-export an object after editing it, which then triggers a new assemblyWF without correctly versioning things, which then possibly causes a version mismatch error.

This is perhaps related to wanting better re-accessioning:

    sul-dlss/argo/issues/1147
    sul-dlss/pre-assembly/issues/423

**Comment by ndushay** [comment]
@peetucket can this be closed?  Is re-accessioning from goobi now dealing with versions correctly?

**Comment by peetucket** [comment]
yes - tested in stage and deployed to -prod and haven't heard of any complaints
