### ISSUE TITLE
jp2-create fails when too many objects with large images are run simultaneously.

### ISSUE THREAD

**Issue by calavano** [sul-dlss/common-accessioning#364]
We've been seeing jp2-create fail with projects with large images--images that are in the 100s of megabytes. The errors will occur with a higher frequency when batches of 30+ objects are queued for jp2-create. When the objects are queued for jp2-create in small batches of <10, they do not have any errors.

There were some changes made to the assembly-image gem to help mitigate this problem by limiting the amount of ram and cpu threads both convert and kdu_compress are allowed to use, but it looks like the there are still too many processes run simultaneously. 

The throttling in the assembly-image gem are already fairly conservative, so I would suggest we either a) have a smaller number of concurrent jp2-create robots running, or b) increase the resources of common-accessioning machines.

There are two examples of the errors that get thrown:

This first error is clear that the problem is with /imtmp/ getting full. 

```
jp2-create : tiff convert command failed: MAGICK_TEMPORARY_PATH=/imtmp convert -quiet -compress none -limit memory 1GiB -limit map 1GiB -type TrueColor -profile /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/assembly-image-1.7.5/profiles/AdobeRGB1998.icc -profile /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/assembly-image-1.7.5/profiles/sRGBIEC6196621.icc '/dor/assembly/jx/233/ps/8560/jx233ps8560/content/jx233ps8560_0001.tif[0]' '/imtmp/assembly-image20190807-2484-btmio4.tif' with result convert: unable to write pixel cache '/imtmp/magick-2500vKEi66oE3N1T': No space left on device @ error/cache.c/WritePixelCachePixels/5823. convert: no images defined `/imtmp/assembly-image20190807-2484-btmio4.tif' @ error/convert.c/ConvertImageCommand/3273.
```

This 2nd suggests that the convert command had a problem--I would expect the convert command to throw an error before it gets here. kdu_compress throws the same error `Kakadu Error: Unable to open TIFF source file` for both a missing file and a corrupt/empty file, so its unknown what state the temp tiff is in based on the error.

```
jp2-create : JP2 creation command failed: kdu_compress -jp2_space sRGB -num_threads 2 -precise -no_weights -quiet Creversible=no Cmodes=BYPASS Corder=RPCL Cblk=\{64,64\} Cprecincts=\{256,256\},\{256,256\},\{128,128\} ORGgen_plt=yes -rate 1.5 Clevels=5 Clayers=9 -i '/imtmp/assembly-image20190807-12425-6g5r3f.tif' -o '/dor/assembly/jr/770/km/7559/jr770km7559/content/jr770km7559_0001.jp2' 2>&1 with result Kakadu Error: Unable to open TIFF source file, "/imtmp/assembly-image20190807-12425-6g5r3f.tif".
```

**Comment by mjgiarlo** [comment]
@sul-devops-team @sul-dlss/operations @sul-dlss/devops Hi, can we bump up the size of `/imtmp` volume on the common-accessioning-prod-* boxes from ~100G to ~200G?

**Comment by mjgiarlo** [comment]
Related to/affected by: https://github.com/sul-dlss/operations-tasks/issues/1993

**Comment by mjgiarlo** [comment]
@calavano 	Do you think we still ought to increase the size of the IM temp volume?

**Comment by mjgiarlo** [comment]
@calavano 	shall we close this issue as well, for now?

**Comment by calavano** [comment]
We're still seeing some fail in a large batch. Some objects are showing up with the error:

```
jp2-create : JP2 creation command failed: kdu_compress -jp2_space sRGB -num_threads 2 -precise -no_weights -quiet Creversible=no Cmodes=BYPASS Corder=RPCL Cblk=\{64,64\} Cprecincts=\{256,256\},\{256,256\},\{128,128\} ORGgen_plt=yes -rate 1.5 Clevels=5 Clayers=10 -i '/imtmp/assembly-image20190814-6883-d3utei.tif' -o '/dor/assembly/pd/707/fs/6018/pd707fs6018/content/pd707fs6018_0001.jp2' 2>&1 with result Kakadu Error: Unable to open TIFF source file, "/imtmp/assembly-image20190814-6883-d3utei.tif".
```

Re-running it as a single object worked. I'm trying to replicate the problem locally.

**Comment by mjgiarlo** [comment]
For first responders... @jermnelson @peetucket Keep an eye on this one tomorrow and next week.

**Comment by mjgiarlo** [comment]
> We're still seeing some fail in a large batch. Some objects are showing up with the error:
> 
> ```
> jp2-create : JP2 creation command failed: kdu_compress -jp2_space sRGB -num_threads 2 -precise -no_weights -quiet Creversible=no Cmodes=BYPASS Corder=RPCL Cblk=\{64,64\} Cprecincts=\{256,256\},\{256,256\},\{128,128\} ORGgen_plt=yes -rate 1.5 Clevels=5 Clayers=10 -i '/imtmp/assembly-image20190814-6883-d3utei.tif' -o '/dor/assembly/pd/707/fs/6018/pd707fs6018/content/pd707fs6018_0001.jp2' 2>&1 with result Kakadu Error: Unable to open TIFF source file, "/imtmp/assembly-image20190814-6883-d3utei.tif".
> ```
> 
> Re-running it as a single object worked. I'm trying to replicate the problem locally.

This is the same as the second error in your original write-up above, right? And we have yet to pinpoint what's happening w/ these. Thanks for troubleshooting.

**Comment by calavano** [comment]
Yes, same error.

The problem indicates that the convert either fails to properly create the temporary tiff without raising an error. kdu_compress will throw the same error if the source tiff passed to it is corrupt/invalid or if it doesn't exist. It is behaving as if convert fails but assembly-image still has `$CHILD_STATUS.success?` return true.

My first guess is that convert is timing out in a way that is returning an successful exit code.

**Comment by peetucket** [comment]
Looks like according this file, we still have 5 jp2 workers? https://github.com/sul-dlss/common-accessioning/blob/master/config/resque-pool.yml

Its an extreme experiment, but how about we chop it down to 1 and see what happens?  Worst case, we get a backlog.

**Comment by mjgiarlo** [comment]
@peetucket I'd be interested to hear what @calavano would think about that.

**Comment by calavano** [comment]
@mjgiarlo @peetucket The queue for large images is back down to 0, so we don't have anything sitting in a queue right now. I can work with the maps team to get a handful of images next week to test it with 1 robot.

**Comment by peetucket** [comment]
Sounds good.

________________________________

**Comment by peetucket** [comment]
Can test later next week by either deploying or merging this PR: #371

**Comment by mjgiarlo** [comment]
Thx, @peetucket

**Comment by peetucket** [comment]
Hi @calavano , any updates on if this is still occurring now that we are single threaded with JP2-create?

**Comment by ndushay** [comment]
Remaining for this ticket:

If the fix addresses the problem and  @calavano is happy with performance, this ticket can be closed.

If @calavano is not happy with performance, we to do something ...

If the fix didn't / doesn't address the problem, we to do something else ...
