### ISSUE TITLE
error for "descMetadata missing required fields (<title>)" sometimes occurs when a title is present in descMetadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#386]
Some objects are stopping at descriptive-metadata with the following error

```descriptive-metadata : descMetadata missing required fields (<title>)```

but when users investigate, they find a descMetadata stream exists and has a title. Setting the step to "waiting" clears up the problem because the title is present at that point and the subsequent check is successful.

Approximately 50 ETDs have been caught at this step in the past two days. Some other users have seen the problem as well, outside of the ETD workflow.

It's possible that the check is running before the descMetadata datastream has been created.

I've put a question to non-ETD users to try to find out if this is always happening now or only sometimes happening but I have not heard back beyond the initial reports.

**Comment by ndushay** [comment]
I looked over the code, and I checked the code with a colleague, and I think we *might* be at this point:

- Ben's uber ticket #188  said that sometimes retrieving stuff from Symphony came back with no results ... but was hard to track.   We put in this check so accessioning would fail on the correct step - the one where re-running the step can fix the problem.  

Earlier today, I found this error on a couple of objects in Argo (prod).  There was no descriptiveMetadata in the object;  I reset this step to waiting, and voila, accessioning happened.  However, the error didn't clear from the item view immediately -- I had to hit "reindex" -- which will happen on its own, eventually on some schedule I don't know.

I would be delighted to have an example of a specific case where this error appears AND reindexing doesn't clear the error AND the descriptiveMetadata is there and has a title.

**Comment by andrewjbtw** [comment]
I was hoping for another example with all the conditions you describe, but nothing seems to have come through like that today.

However, the number of items in this state with no catkey and no descMetadata seems unusually high and makes me wonder if there's something else going on with how that datastream is created that might be unrelated to this ticket. I've tried resetting a number of these (no catkey, no descmetadata) and they get caught again. I've reindexed but not seen a change. Maybe it will look different Monday.

**Comment by andrewjbtw** [comment]
I checked with the content owner on items that are missing the descMetadata datastream altogether and determined that is unrelated to this ticket. Certain old objects have this problem, so it was expected that those items would be caught at this step.

I will continue to keep an eye out for more objects that fail at this step and do have a title.

**Comment by ndushay** [comment]
talk to @andrewjbtw for latest info;  we think the ETD workflow may trigger this.   https://consul.stanford.edu/display/ETD/ETD+Submission+Workflow

descriptive metadata is supplied in the ETD app's own workflow but under catalog status there’s this note: “Common Accessioning will later fetch the latest version of MARC to create MODS for descMetadata.”

**Comment by andrewjbtw** [comment]
Another druid is caught at this step with a descMetadata and a title https://argo.stanford.edu/view/druid:gy837pv2430 

In this case it's not an ETD, so it must not be only ETDs that can get caught here.

**Comment by ndushay** [comment]
I've started 3 different answers as to why this is true ... and in each case, my theory proved wrong.   I feel like I'm getting pulling into deep debugging of a handful of cases where the new checks are "problematic" ... and I'm not sure if that is warranted at this time or not.   @andrewjbtw can you assess if this is "yes, we need to figure this out this work cycle" or "this could be a first responder thing" or "this can wait" ?

I want to provide great customer service, but I also want to spend my time on the highest priority stuff for you.

**Comment by ndushay** [comment]
It *may* be that https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/desc_metadata_ds.rb  needs to be aware of attribute "type=alternative" to distinguish the main title as https://argo.stanford.edu/view/druid:gy837pv2430 has:

```
  <titleInfo>
    <title>[Hank Schwager Collection]</title>
  </titleInfo>
  <titleInfo type="alternative">
    <title>Schwager Collection</title>
  </titleInfo>
```

**Comment by ndushay** [comment]
Update:   https://argo.stanford.edu/view/druid:gy837pv2430 , upon re-index, no longer had a hung "releaseWF", which allowed a "set to waiting" on the descMetadata step, which then processed smoothly.  (It hit another error, but that is irrelevant here)

**Comment by ndushay** [comment]
I'm pretty sure PR #394 fixes this, and it should be deployed to prod Monday morning.

**Comment by ndushay** [comment]
PR #394 has been deployed;  Andrew was able to remediate the objects caught between states to clear all descMetadata errors;  the workflow grid shows NO descMetadata errors.

I'm closing this ticket;  if that's incorrect, please re-open it, or open a new one.
