### ISSUE TITLE
Update common-accessioning to use newer release of jhove-service

### ISSUE THREAD

**Issue by calavano** [sul-dlss/common-accessioning#410]
The current deploy of jhove-service uses jhove 1.14.6 which is causing objects to fail in technical-metadata. The version in the newest branch uses 1.20.1 and fixes these problems. 

Examples of the objects failing because of it are:
druid:ks198dg9130
druid:cx806dv7903
druid:xq775hq1450

**Comment by mjgiarlo** [comment]
Done in https://github.com/sul-dlss/common-accessioning/pull/413. Closing.
