### ISSUE TITLE
Figure out how to get rid of DatastreamBuilder.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#417]
One thing that DatastreamBuilder does is to look for an appropriately named file and then see if it's timestamp is newer than the existing datastream timestamp.  If the file is newer, it is added as the new datastream.  The comments indicate that pre-assembly uses this, but it's not clear what datastreams (contentMetadata, descriptiveMetadata, rightsMetadata, technicalMetadata) we actually attach using this mechanism. 

To switch to a JSON model, we won't have timestamps on datastreams, so we need to design a new mechanism for this.

Perhaps:
  - delete the file after adding it
  - have preassembly set the values via a new api in dor-services-app rather than depending on an accession workflow to do it.
  - ???

- [x] descMetadata https://github.com/sul-dlss/common-accessioning/pull/456
- [x] contentMetadata https://github.com/sul-dlss/common-accessioning/pull/469
- [ ] rightsMetadata
- [ ] technicalMetadata

**Comment by mjgiarlo** [comment]
@jcoyne FWIW, this code path has been used 51 times since 11/18: https://app.honeybadger.io/projects/52894/faults/57531424

**Comment by jcoyne** [comment]
This work is complete
