### ISSUE TITLE
Merge Accessioning end-accession and Dissemination workflow.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#428]
https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/accession/end_accession.rb#L19-L20

https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/dissemination/cleanup.rb#L12

The end-accession step calls dissemination workflow, which only has one step, which is to call cleanup.  The could be merged into reset-workspace.

**Comment by mjgiarlo** [comment]
Need to talk with @andrewjbtw about whether this is a useful or duplicative practice. If the latter, consider in-scope for GBooks SDR Evolution WC.

**Comment by jcoyne** [comment]
Ensure no tie to web-archiving

**Comment by jcoyne** [comment]
Talked with @andrewjbtw and he said, that he can't see why this needs to exist on its own.

**Comment by ndushay** [comment]
the `end-accession` step calls `startSpecialDissemination`, which signals to was_robots_suite dissemination robot to trigger (and then call either seed or crawl dissemination).   So the trick will be to ensure that if we combine the steps in some way, the ordering doesn't fooch the web-archiving stuff (by removing things too soon?) or the last step somehow.  

Justin and I quickly looked over the code and believe there is no conflict but it wouldn't hurt to double check.

**Comment by ndushay** [comment]
do we need to make any changes to any workflows expectations and/or will there be any problems for objects stuck in processing the old way when we go to the new way?

**Comment by mjgiarlo** [comment]
Do you have thoughts on @ndushay's question above, @jcoyne?

**Comment by jcoyne** [comment]
Shouldn't be a problem as there's nothing stopped in those steps.

**Comment by justinlittman** [comment]
@ndushay @mjgiarlo @jcoyne Anything else need to be done for this ticket other than https://github.com/sul-dlss/common-accessioning/pull/563?

I reviewed the mention of dissemination WF in other repos and don't see anything else that needs to be changed.

**Comment by mjgiarlo** [comment]
@justinlittman Not that I am aware of.
