### ISSUE TITLE
Migrate from sdr-services-app to preservation_catalog

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#448]
We have two projects that act on the SDR, we should consolidate into one.

✔️ This may require moving some functionality from one sdr-services-app to preservation_catalog.
✔️ Then alter common accessioning to use the endpoint provided by preservation_catalog
Finally, create a ticket to decommission sdr-services-app.

- [x] preservation_catalog API can do all the things we need from sdr-services-app
- [x] preservation-client gem can be used to interact with preservation-catalog
- [x] consumers of sdr-services-app (via dor-services-client or dor-services-app) use preservation-client gem instead
    - [x] dor-services-app
        - [x] `current_version` for version_service
        - [x] `content_diff` for shelving service
        - [x] signature_catalog (metadata) for SdrIngestService (robot handoff from common-accessioning to preservation robots)
    - [x] common-accessioning
        - [x] `metadata` (to get technicalMetadata.xml)
        - [x] `content_diff` to update technicalMetadata
    - [x] argo
        - [x] `current_version`
        - [x] `checksum report`
        - [x] `content` (retrieve preserved content files)
- [x] sdr-services-app calls deprecated
- [x] dor-services-app calls to sdr-services-app deprecated
- [x] dor-services-client calls to ^^ are deprecated
- [ ] wait and watch honeybadger and sdr-services-app logs for any missed calls
- [ ] dor-services-app: remove sdr-services-app calls (already deprecated) and release v4.0.0
- [x] dor-services-client: remove calls to ^^ (already deprecated) and release v4.0.0 https://github.com/sul-dlss/dor-services-client/pull/122

sdr-services-app: decommission stuff is in this ticket sul-dlss/sdr-services-app/issues/104

**Comment by ndushay** [comment]
who should this be assigned to?  @jmartin-sul ?  @jcoyne ?
