### ISSUE TITLE
Investigate (and remediate) technical metadata errors from Monday

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/common-accessioning#484]
For objects accessioned between 8:45am and 10:45am on Monday, December 16th, check that the technical metadata is correct, particularly for objects at version > 1.

Identify these objects with Patch requests sent to preservation_catalog.

Steps: 
1. figure out which objects were affected; 
1. figure out HOW they were affected; and
1. figure out how to remediate them (needs discussion, set that up)

**Comment by ndushay** [comment]
- `tb352ws1306` - a very old (2015) broken looking object with no versions.
- `sr961jg6195`
- `nr758rg7861`
- `qv347fp4653` - v1 media object -- no techMd issues

**Comment by ndushay** [comment]
@andrewjbtw just tagging you to let you know I'm confident we didn't create bad techMd during the "incident" and the only 4 records processed in the window appear to be unaffected.
