### ISSUE TITLE
trap for preservation-client errors and handle accordingly

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#485]
common-accessioning uses preservation-client in the following ways:
- creating technical metadata step
    - getting previous version's technical metadata from preservation ("manifest")
    - getting diff between current content and previous version's content files ("content_inventory_diff")
- shelving step
   - use dor-services-app, which uses preservation-client to get content diff for shelved files

common-accessioning code should trap for any errors or unexpected status codes (i.e. not a 200) from preservation-client or dor-services-client and:
- fail the workflow step as appropriate
- notify honeybadger as appropriate
- log error messages as appropriate

See https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client.rb#L30-L39

**Comment by jcoyne** [comment]
common-accessioning is already set up so that it traps any raised error and set's the current workflow step (in the workflow service) as failed, logs the error and alerts Honeybadger.  This is done by the lyber-core gem.   I'm not sure that we need to make any changes.

**Comment by peetucket** [comment]
Here are a couple example exceptions caught and sent to honeybadger from the pres-client gem and the robots:

https://app.honeybadger.io/projects/52894/faults/58727457
https://app.honeybadger.io/projects/52894/faults/58481982

**Comment by peetucket** [comment]
From Slack from @jcoyne on Dec 18 at 12:53pm:

```
To follow up, it looks like the preservation client was correctly throwing errors in dor-services-app.  Argo and pre-assembly was consuming this, so no versions were able to be opened until we patched dor-services app at 10:25 (https://app.honeybadger.io/projects/50568/faults/55192133) 

So we probably didn't cause much damage until after 10:25 Monday  (and before 11:56 Tuesday) when we thought we had objects going to preservation, but they never were because the preservation robots were not following the redirect.
```

**Comment by peetucket** [comment]
Based on this, we don't think any action is needed at the moment.
