### ISSUE TITLE
Recreate tech metadata for all files in the workspace

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#490]
... rather than merge with existing technical metadata

@andrewjbtw says that all files have to be staged in the workspace anyway, so there's no need to merge with old techmd from production.  This significantly reduces the complexity of the technical metadata generation.    

Do #491 first.

**Comment by mjgiarlo** [comment]
This ticket is subsumed by the work to handle technical metadata in its own db-backed service, using file identification and format-specific characterization tools. Closing.
