### ISSUE TITLE
Create a warning if technical metadata step doesn't have the file staged.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#491]
Leave this in place for a month or so to see if this ever happens.

**Comment by ndushay** [comment]
Ben says in the past there have been other ways, but they are not recommended and they might no longer work.

**Comment by andrewjbtw** [comment]
To make sure I understand the situation: what we're looking for is if a reaccession includes only new files for an existing Moab in the accessioning workspace, where existing files in the Moab already have techMD and so in the current system wouldn't have that techMD regenerated.

The proposed change to always regenerate techMD for new versions assumes that all files will be present each time reaccessioning takes place, so it will be a problem if certain reaccessioning methods don't include all the files.

**Comment by jcoyne** [comment]
@andrewjbtw  yes, that is my understanding as well.

**Comment by mjgiarlo** [comment]
@jcoyne This issue (in the out-of-scope pipeline) is blocking https://github.com/sul-dlss/common-accessioning/issues/490 (in the backlog pipeline). Should this issue be moved back in scope?

**Comment by jcoyne** [comment]
@mjgiarlo I think @justinlittman might already have this done.

**Comment by mjgiarlo** [comment]
@justinlittman what do you say?

**Comment by justinlittman** [comment]
Yes, this experiment is in place.
