### ISSUE TITLE
Long running tasks get duplicated

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#505]
1. When a job is running, the status is 'queued' as set by (https://github.com/sul-dlss/workflow-server-rails/blob/54492b3dfe53164c7474fcb90c324da340045e13/app/services/queue_service.rb#L24)
1. If the job is running for more than 12 hours the sweeper comes by and creates a new version of it (https://github.com/sul-dlss/workflow-server-rails/blob/master/app/services/sweeper.rb#L21-L23)

This could be fixed by creating a "running" status here: https://github.com/sul-dlss/workflow-server-rails/blob/master/app/models/workflow_step.rb#L10
and updating the state to "running" here: https://github.com/sul-dlss/lyber-core/blob/master/lib/lyber_core/robot.rb#L61

**Comment by justinlittman** [comment]
* Also, probably need to make changes in the robot-like dor-services-apps jobs.
* I'm calling the status "started" as "running" suggests that the task is actually running, when, for example, it may have crashed.

**Comment by mjgiarlo** [comment]
Hi, @justinlittman. What is the status of this issue?

**Comment by justinlittman** [comment]
Waiting until next week to roll out the final part: https://github.com/sul-dlss/workflow-server-rails/pull/327

**Comment by mjgiarlo** [comment]
@justinlittman OK. Cool if I pop this over to "In Progress?"

**Comment by justinlittman** [comment]
Sure.

**Comment by mjgiarlo** [comment]
@justinlittman Are you ready to roll out the final part?

**Comment by mjgiarlo** [comment]
@justinlittman deployed https://github.com/sul-dlss/workflow-server-rails/pull/327 to production earlier today. We will continue monitoring the behavior of workflow steps in the meantime and revisit this.

**Comment by mjgiarlo** [comment]
I recommend we let this stick around a week or so and then re-assess. @jcoyne - check in on this next Weds or so?

**Comment by ndushay** [comment]
Is this issue addressed, or what?  @jcoyne @justinlittman
