### ISSUE TITLE
Draw conclusions about  tech metadata experiment: checking for all files staged

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#519]
This experiment: https://github.com/sul-dlss/common-accessioning/commit/c7c45ff4bd3889f33a57b93a9be489f98bbb1f73

is now yielding results.  Can we draw any conclusions?
## Backtrace

    line 57 of [PROJECT_ROOT]/lib/technical_metadata_service.rb: rescue in check_all_files_staged
    line 54 of [PROJECT_ROOT]/lib/technical_metadata_service.rb: check_all_files_staged
    line 26 of [PROJECT_ROOT]/lib/technical_metadata_service.rb: add_update_technical_metadata

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/59958778)

**Comment by mjgiarlo** [comment]
I believe checking in on this experiment to see what we've learned is now ready to be done.

**Comment by justinlittman** [comment]
@jcoyne @mjgiarlo Can we just close this? Given the new approach to technical metadata, this doesn't matter.

**Comment by jgreben** [comment]
We haven't seen any case where they haven't staged everything. Closing.
