### ISSUE TITLE
If an object has no files, don't run technicalMetadata or shelve robots

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#540]
Presently if there are no files (no contentMetadata.xml) then it tries to get content_md_diff from preservation with nil which causes preservation catalog to raise an error.

This may have behaved differently when we had sdr-services-app in the stack.

we have decided that it's clearer if the robots skip technical_metadata and shelve if there are no files.

**Comment by ndushay** [comment]
I added this to prod probs sheet (open issues) and indicated jcoyne was working on it.

**Comment by ndushay** [comment]
here's a stupid thought:  will it work if we decide to add a file to such an object later?  (like v1 has no content, but v2 does have content ... I think this may occur - @andrewjbtw ?)

**Comment by jcoyne** [comment]
@ndushay then v2 would have contentMetadata.xml and there wouldn't be a problem
