### ISSUE TITLE
New APOs won't accession

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#556]
## Backtrace

    line 27 of [PROJECT_ROOT]/lib/robots/dor_repo/accession/rights_metadata.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/60510452)

**Comment by mjgiarlo** [comment]
Part of the problem was resolved by https://github.com/sul-dlss/dor-services-app/pull/633
