### ISSUE TITLE
Embargo-release date queries are failing due to solr field name changes

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/common-accessioning#56]
Looking for assistance in a current production service failure with releasing embargoed items.  We have not released any embargoed items, some 91 of them, since 3/25, or the date of the new Argo index.  The embargo-release process that runs nightly looks for embargoed items that have passed their release date, but have been finding none since the Argo big release because of solr field name changes, to wit…

Here are the now failing queries as shown in the log:

***** Querying solr: embargoMetadata_status_t:'embargoed' AND embargo_release_date_dt:[* TO NOW]
***** Querying solr: embargoMetadata_twenty_pct_status_t:'embargoed' AND twenty_pct_visibility_release_date_dt:[* TO NOW]

And here are the new, correct solr field names …

from https://argo.stanford.edu/catalog/druid:bb553jj1249.json

   embargo_status_ssim": [
   "embargoed"
   ],
   "embargo_release_dtsim": [
   "2016-05-08T00:00:00Z”
   ]

from https://argo.stanford.edu/catalog/druid:fv292gt8921.json

  "twenty_pct_status_ssim": [
  "embargoed"
  ],
  "twenty_pct_visibility_release_dtsim": [
  "2020-07-22T00:00:00Z"
  ],

The code is in https://github.com/sul-dlss/common-accessioning/blob/master/robots/accession/embargo_release.rb and is currently deployed to sul-robots1-prod.stanford.edu.

**Comment by drh-stanford** [comment]
This looks like a straight-forward update in the Solr field names in the `release` method here https://github.com/sul-dlss/common-accessioning/blob/master/robots/accession/embargo_release.rb#L56-L65

**Comment by LynnMcRae** [comment]
The embargo-release run last night continied to fail to find any candidate objects for release ...
```
 INFO [2016-05-31 02:16:03] (9571)  :: ***** Querying solr: embargoMetadata_status_t:'embargoed' AND embargo_release_date_dt:[* TO NOW]
 INFO [2016-05-31 02:16:03] (9571)  :: No objects to process
 INFO [2016-05-31 02:16:03] (9571)  :: ***** Querying solr: embargoMetadata_twenty_pct_status_t:'embargoed' AND twenty_pct_visibility_release_date_dt:[* TO NOW]
 INFO [2016-05-31 02:16:03] (9571)  :: No objects to process

 INFO [2016-06-01 02:16:05] (21862)  :: ***** Querying solr: embargo_status_ssim:'embargoed' AND embargo_release_dtsim:[* TO NOW]
 INFO [2016-06-01 02:16:05] (21862)  :: No objects to process
 INFO [2016-06-01 02:16:05] (21862)  :: ***** Querying solr: twenty_pct_status_ssim:'embargoed' AND twenty_pct_visibility_release_dtsim:[* TO NOW]
 INFO [2016-06-01 02:16:05] (21862)  :: No objects to process
```
so I fear this is not fixed.  Is there an issue with the new fields themselves, in how they are searched?

**Comment by drh-stanford** [comment]
@tingulfsen looks like the Solr query is indeed returning no documents.

```
[7] pry(main)> q
=> "embargo_status_ssim:'embargoed' AND embargo_release_dtsim:[* TO NOW]"
[8] pry(main)> solr.get 'select', :params => { :q => q }
=> {"responseHeader"=>
  {"status"=>0, "QTime"=>1, "params"=>{"q"=>"embargo_status_ssim:'embargoed' AND embargo_release_dtsim:[* TO NOW]", "wt"=>"ruby"}},
 "response"=>{"numFound"=>0, "start"=>0, "maxScore"=>0.0, "docs"=>[]},
 "facet_counts"=>
  {"facet_queries"=>{},
   "facet_fields"=>{"active_fedora_model_ssi"=>[], "object_type_si"=>[]},
   "facet_dates"=>{},
   "facet_ranges"=>{},
   "facet_intervals"=>{},
   "facet_heatmaps"=>{}},
 "spellcheck"=>{"suggestions"=>[], "correctlySpelled"=>false}}
```

but looks like the document fields we have are correct too:

```
      "embargo_status_ssim"=>["embargoed"],
      "embargo_release_dtsim"=>["2014-03-12T00:00:00Z"],
```

**Comment by drh-stanford** [comment]
if i remove the single quotes, i do get results, but my understanding is that the quoting is correct.

```
=> {"responseHeader"=>
  {"status"=>0,
   "QTime"=>3,
   "params"=>
    {"q"=>"embargo_status_ssim:embargoed AND embargo_release_dtsim:[* TO NOW]", "fl"=>"embargo_status_ssim", "wt"=>"ruby"}},
 "response"=>
  {"numFound"=>117,
   "start"=>0,
   "docs"=>
    [{"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]},
     {"embargo_status_ssim"=>["embargoed"]}]},
 "facet_counts"=>
  {"facet_queries"=>{},
   "facet_fields"=>{"active_fedora_model_ssi"=>["Dor::Item", 117], "object_type_si"=>[]},
   "facet_dates"=>{},
   "facet_ranges"=>{},
   "facet_intervals"=>{},
   "facet_heatmaps"=>{}},
 "spellcheck"=>{"suggestions"=>[], "correctlySpelled"=>true}}
```

**Comment by drh-stanford** [comment]
Talked to Tommy briefly. The `embargoMetadata_status_t` and `embargo_status_ssim` may be different data types in the Solr index, which might explain a need to change the query.

**Comment by LynnMcRae** [comment]
OK, what's going on now. This is a job that ran fine up until the solr field name changes, and continued to run fine getting zero results every day.  This might be a different ticket since it's not the solr field names, but embargo-release did not run properly:
---
 INFO [2016-06-02 02:16:03] (20185)  :: ***** Querying solr: embargo_status_ssim:"embargoed" AND embargo_release_dtsim:[* TO NOW]
 INFO [2016-06-02 02:16:04] (20185)  :: Found 127 objects
 INFO [2016-06-02 02:16:04] (20185)  :: Releasing embargo for druid:bt714mb5092
ERROR [2016-06-02 02:16:05] (20185)  :: !!! Unable to release embargo for: druid:bt714mb5092
#<Errno::ENOENT: No such file or directory @ rb_sysopen - log/wfs/workflow_service.log>
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:636:in `create_logfile'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:630:in `rescue in open_logfile'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:627:in `open_logfile'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:318:in `new'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor/config.rb:86:in `new'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor/config.rb:86:in `block (2 levels) in <class:Configuration>'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/utils.rb:7:in `call'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/utils.rb:7:in `eval_or_yield'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/hash_with_struct_access.rb:85:in `[]'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/hash_with_struct_access.rb:189:in `method_missing'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor/config.rb:81:in `block (2 levels) in <class:Configuration>'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/utils.rb:7:in `call'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/utils.rb:7:in `eval_or_yield'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/hash_with_struct_access.rb:85:in `[]'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/confstruct-0.2.7/lib/confstruct/hash_with_struct_access.rb:189:in `method_missing'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor/models/versionable.rb:19:in `open_new_version'
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:41:in `block in release_items'
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `each'
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `release_items'
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:57:in `release'
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:67:in `<main>'
```

**Comment by drh-stanford** [comment]
This looks like a different issue. In fact, it looks like a simple fix -- that the `log/wfs` folder does not exist in the place where embargo_release is running. 

The crontab looks broken to me -- it should `cd $HOME/common-accessioning/current` before it runs.

```
16 2 * * * /bin/bash -l -c 'BUNDLE_GEMFILE=/home/lyberadmin/common-accessioning/current/Gemfile ROBOT_ENVIRONMENT=test /usr/local/rvm/wrappers/default/ruby /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb >> /home/lyberadmin/common-accessioning/current/log/crondebug.log 2>&1'
```

**Comment by tingulfsen** [comment]
Thanks, Darren. I figured it might be a configuration change. I'll change it and the crontab setup, then we'll see.

**Comment by jmartin-sul** [comment]
the feeling in the current margo planning meeting is that we should close this one and open a new one for the cron job thing, since the initial issue is technically fixed.  for tracking work, creating a proxy ticket in media: https://github.com/sul-dlss/media/issues/68

**Comment by jmartin-sul** [comment]
leaving this open for the actual common-accessioning work and discussion.  closed the first media proxy ticket, left the second one open for the cron job part.
