### ISSUE TITLE
Draw conclusions about descMetadata experiment: running refresh_metadata

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/common-accessioning#569]
[This experiment](https://github.com/sul-dlss/common-accessioning/pull/550/files) has been running a while. We should see what have learned for SDR evolution. Is this a valid code path or not? Can we draw any conclusions?

**Comment by jcoyne** [comment]
Now that we require a title in DSA (https://github.com/sul-dlss/dor-services-app/commit/d5ae6d4b7754d84b0e552ad8e7e3e018d51b5f8c), I think we can conclude, this code path is dead.

**Comment by jcoyne** [comment]
We need to consider this case in our current approach: https://argo-stage.stanford.edu/view/druid:bd401tg8156  It has descMetadata, but not the mods fullTitle

**Comment by andrewjbtw** [comment]
There is a real-world situation where we have gotten descMetadata without a title: in the past, when many druids were registered to the same catkey at the same time, Symphony has returned MODS for only one of the druids and an incomplete descMetadata has been created for the rest of them. We think that Symphony isn't able to handle many simultaneous requests for the same catkey.

I will try to reproduce this in stage.

**Comment by andrewjbtw** [comment]
For what it's worth, I registered over 200 items to the same catkey in stage and there wasn't a problem pulling in the metadata for all of them, so it looks like we don't need to worry about that case. This matches a real-world example of many maps registered to one catkey in production from last year.

**Comment by mjgiarlo** [comment]
Thank you, @andrewjbtw!
