### ISSUE TITLE
Install Siegfried

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#570]
Ticket to install Siegfried: https://www.itforarchivists.com/siegfried/

A CentOS package can be found in the Archivematica packages repository: https://packages.archivematica.org/1.10.x/centos-extras/

**Comment by rsmith11** [comment]
The package should be installed on the production common-accessioning servers.  The stage ones are at Centos6, and the package from the repo is for Centos7 systems.  I will be putting out a upgrade document later to plan to upgrade the stage servers to Centos7.

**Comment by mjgiarlo** [comment]
@rsmith11 We will do this in the technical metadata service, not in common-accessioning. Closing. Will re-open in that context during sprint 4.
