### ISSUE TITLE
Install technical metadata tools

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#572]
Related to #555 

Please install the following tools for testing and evaluation for technical metadata generation:

- Exiftool -- https://exiftool.org/

I believe this might already be installed and used elsewhere in SDR

Exiftool is most focused on image formats, but does have some support for document/office formats. It has a JSON output option.

- Mediainfo -- https://mediaarea.net/en/MediaInfo

There are CentOS packages: https://mediaarea.net/en/MediaInfo/Download/CentOS

Mediainfo is specifically for A/V formats. It has a JSON output option.

-----
**Decision: hold off on installing these two unless we need them later**

- Apache Tika -- https://tika.apache.org/

Tika may be the best tool for office document metadata but it's Java-based so we might not even want to try it. A suggestion I've gotten is to run it as a server, but that might be more overhead than it's worth. Information on the server application is here: https://cwiki.apache.org/confluence/display/TIKA/TikaJAXRS

- Sleuthkit -- https://www.sleuthkit.org/sleuthkit/

This includes the "fiwalk" command, which generates metadata from disk image formats. This would allow us to make directory listings for ISO and other files. But the standard way of doing this produces an XML file (Digital Forensics XML https://en.wikipedia.org/wiki/Digital_Forensics_XML ) and we are not currently taking in many disk images. We could hold off on this until we get more accessioning and input from the Born Digital Forensics Lab.

**Comment by rsmith11** [comment]
Are these to be installed on the common-accessioning systems, or is this similar to the request to build the dor-techmd systems https://github.com/sul-dlss/technical-metadata-service/issues/1

**Comment by andrewjbtw** [comment]
I didn't realize we had a new place for that when I filed this ticket -- @jcoyne?

**Comment by mjgiarlo** [comment]
@rsmith11 You're right: these will not go on common-accessioning but on the techmd service. thanks! Closing
