### ISSUE TITLE
[HOLD] Integrate technical-metadata-service

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#575]
For integrating the new technical metadata service:
1. TechMd robot marks the workflow step as started.
2. TechMd robot invokes TechMd service via HTTP call and exits without updating workflow step status.
3. TechMd service queues a job.
4. When job is executed, it performs techmd generation, and then updates workflow step (as either succeeded or failed).

(In the future when message broker, could get rid of robot and direct communication with workflow service.)

**Comment by jcoyne** [comment]
@justinlittman is there are related ticket in lyber-core for "exits without updating workflow step status." ?

**Comment by jcoyne** [comment]
NM, I found https://github.com/sul-dlss/lyber-core/pull/53
