### ISSUE TITLE
[ÜBER] Decouple ETD robots from Fedora 3

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#582]
There should be no calls to `ETD.find`
in these classes:
EtdSubmit::CheckMarc
EtdSubmit::OtherMetadata
EtdSubmit::SubmitMarc

**Comment by jcoyne** [comment]
It looks like completely decoupling the etd robots will not be possible until we modify hydra_etd to use the deposit endpoint.  The etd robots depend on some non-standard datastreams (properties for one) that don't map to cocina models.

**Comment by ndushay** [comment]
I *think* PR #591 does this, not sure of the diff between this ticket and #586.

PR #591 gets rid of ETD.find calls;  it does not get rid of all coupling to Fedora 3.

**Comment by jcoyne** [comment]
@ndushay #586 is a smaller scope than this.  This ticket is an uber ticket.

**Comment by mjgiarlo** [comment]
I have marked this ticket as an über.

**Comment by jcoyne** [comment]
Need to rewrite ETDs first because ETDs use non-standard datastreams, which are not supported by cocina.  Maybe we pull the robots stuff into the etd codebase.
