### ISSUE TITLE
Update etd robots to use legacy_metadata api 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#586]
This decouples the writing to fedora 3, which is 1/2 of #582 (the reading part will have to wait until hydra_etd can be rewritten)

**Comment by ndushay** [comment]
From https://github.com/sul-dlss/common-accessioning/issues/582#issuecomment-589858935: 

> It looks like completely decoupling the etd robots will not be possible until we modify hydra_etd to use the deposit endpoint. The etd robots depend on some non-standard datastreams (properties for one) that don't map to cocina models.

**Comment by jcoyne** [comment]
Fixed by #591
