### ISSUE TITLE
Run an integration test of the ETD + robots

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#594]
Specifically, we are looking to see that the etdWF hands off to the accessioningWF and that descMetadata is created.

**Comment by ndushay** [comment]
See also intregation test repo ticket #17

**Comment by jcoyne** [comment]
@ndushay this ticket is just for some manual testing as per: https://github.com/sul-dlss/hydra_etd/wiki/End-to-End-Testing-Procedure
