### ISSUE TITLE
embargo release still failing (stage)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#60]
Idea is to get this working first in stage/test.  The issue below is from that context.

latest issue seems like it might be a dor-workflow-service client config issue, see https://github.com/sul-dlss/media/issues/68#issuecomment-224688267:

```
[lyberadmin@sul-robots1-test ~]$ cd /home/lyberadmin/common-accessioning/current/
[lyberadmin@sul-robots1-test current]$ BUNDLE_GEMFILE=/home/lyberadmin/common-accessioning/current/Gemfile ROBOT_ENVIRONMENT=test /usr/local/rvm/wrappers/default/ruby /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb
Loading config from /home/lyberadmin/common-accessioning/current/config/environments/test
DEPRECATION WARNING: Dor::Config -- solrizer configuration is deprecated. Please use solr instead. (called from <top (required)> at /home/lyberadmin/common-accessioning/current/config/environments/test.rb:3)
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:13: warning: already initialized constant ENABLE_SOLR_UPDATES
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/active-fedora-6.7.3/lib/active_fedora.rb:13: warning: previous definition of ENABLE_SOLR_UPDATES was here
D, [2016-06-07T14:53:16.639176 #1737] DEBUG -- : Loaded datastream list for druid:kn280cs8150 (67.3ms)
D, [2016-06-07T14:53:16.722530 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/RELS-EXT (80.8ms)
D, [2016-06-07T14:53:16.803216 #1737] DEBUG -- : Loaded datastream content druid:kn280cs8150/RELS-EXT (74.5ms)
D, [2016-06-07T14:53:16.885258 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/workflows (76.5ms)
D, [2016-06-07T14:53:21.979189 #1737] DEBUG -- : Loaded datastream list for druid:mt134rb1849 (81.3ms)
D, [2016-06-07T14:53:22.048149 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/RELS-EXT (67.3ms)
D, [2016-06-07T14:53:22.119108 #1737] DEBUG -- : Loaded datastream content druid:mt134rb1849/RELS-EXT (69.2ms)
D, [2016-06-07T14:53:22.180513 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/workflows (59.6ms)
D, [2016-06-07T14:53:22.983316 #1737] DEBUG -- : Loaded datastream list for druid:my974mh9308 (86.0ms)
D, [2016-06-07T14:53:23.089404 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/RELS-EXT (103.3ms)
D, [2016-06-07T14:53:23.153832 #1737] DEBUG -- : Loaded datastream content druid:my974mh9308/RELS-EXT (63.4ms)
D, [2016-06-07T14:53:23.227182 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/workflows (70.1ms)
D, [2016-06-07T14:53:25.788271 #1737] DEBUG -- : Loaded datastream list for druid:px885wv4511 (83.5ms)
D, [2016-06-07T14:53:25.874638 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/RELS-EXT (82.7ms)
D, [2016-06-07T14:53:25.978890 #1737] DEBUG -- : Loaded datastream content druid:px885wv4511/RELS-EXT (102.4ms)
D, [2016-06-07T14:53:26.065019 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/workflows (83.1ms)
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:561:in `rescue in workflow_resource_method': Failed to retrieve resource: put https://lyberservices-test.stanford.edu/workflow//dor/objects/druid:px885wv4511/workflows/disseminationWF/embargo-release (HTTP status 500) (Dor::WorkflowException)
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:551:in `workflow_resource_method'
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:162:in `update_workflow_error_status'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:49:in `rescue in block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:37:in `block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `each'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:57:in `release'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:67:in `<main>’
```

**Comment by ndushay** [comment]
5 objects in stage are failing embargo release.  They are:
* px885wv4511
  * argo-stage:  APO problem
 * getting 404: resource not found;  MoabObject exception (couldn't run SDR current version call)  (Dor::Item.open_new_version)

* mt134rb1849
  * argo-stage:  looks happy
  * getting `Dor::Exception: Object net yet accessioned`  dor-services/lib/dor/models/versionable:18 (Dor::Item.open_new_version)

* bj188qw9596
  * argo-stage: lifecycle shows registered, but nothing else
  * getting `Dor::Exception: Object net yet accessioned`  dor-services/lib/dor/models/versionable:18 (Dor::Item.open_new_version)

* kn280cs8150 (Baby girl Melton)
  * argo-stage: `technical metadata: 401 Unauthorized`
  * getting `Dor::Exception: Object net yet accessioned`  dor-services/lib/dor/models/versionable:18 (Dor::Item.open_new_version)

* my974mh9308
  * argo-stage:  errors with technical-metadata, contentMetadata, accessionWF:shelve
  * getting `Dor::Exception: Object net yet accessioned`  dor-services/lib/dor/models/versionable:18 (Dor::Item.open_new_version)

**Comment by ndushay** [comment]
This is, effectively, the code to do an embargo_release.  

```
embargo_druids.each do | druid |
 item=Dor::Item.find("druid:#{druid}")
 item.open_new_version
 item.release_embargo("application::accessionWF:embargo-release")
 item.close_version :description => "embargo released", :significance => :admin
 item.save
 puts "#{druid} embargo released"
end
```

 We are currently failing on `open_new_version` with `404: resource not found; MoabObject exception (couldn't run SDR current version call)`


We surmise the problem with `open_new_version` is a configuration issue.  We are suspicious of the settings for connect to SDR.

Note that there may be failures with `release_embargo`  after we get `open_new_version` to work.

**Comment by ndushay** [comment]
Theory (for failing SDR request):   common_accesioning code is using old method of connecting to SDR directly rather than going through dor-services app.

Possible Solution?
* upgrade common_accessioning to latest dor-services gem
* update deployed configuration to use new sdr proxy style

estimate:  a "waffle" 3 or maybe a 5 or maybe ...

**Comment by ndushay** [comment]
embargo release processing documented here:  https://github.com/sul-dlss/argo/wiki/Embargo-Release-Processing

**Comment by ndushay** [comment]
An embargoed datastream looks like this
```
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2016-06-13T08:00:00Z</releaseDate>
  <twentyPctVisibilityStatus/>
  <twentyPctVisibilityReleaseDate/>
  <releaseAccess>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
  </releaseAccess>
</embargoMetadata>
```

Embargo release replaces the object level rights in rightsMetadata with the contents of \<releaseAccess> and then sets the status to "release". 

rightsMetadata for an item under embargo looks like this: 
```
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <embargoReleaseDate>2016-06-13T08:00:00Z</embargoReleaseDate>
      <none/>
    </machine>
  </access>
  ...etc...
```

The two expressions of release date should match of course, and be in the past to be caught by the embargo release job's query.

**Comment by ndushay** [comment]
druid:kn280cs8150 and druid:px885wv4511 look like usable examples in stage. I set them both back to being embargoed and can reset them quickly as needed.

**Comment by ndushay** [comment]
sul-robotx-test  
* couldn't run embargo_release script - it craps out on px885wv4511 druid, and never gets to kn280cs8150 druid
* was able to successfully run kn280cs8150 druid in console, just as we were able to do this yesterday.

We ( @jmartin-sul and I) surmise that the config changes alone were enough to fix the problem running the script, because it ran yesterday before he deployed the common_accessioning branch that updated to dor-services v5.8.0 (from v5.7.0).

We wanted to test this theory, so we updated the config on prod and were able to 
* successfully run zp102fc2047 via console by hand
* kicked off the same script the cron job uses for embargo_release and it seems to be happily running.

The config changes we made were for sdr and the fedora key_pass.  We left a copy of the old config on the prod robots boxes just in case.
 
We ported the config changes to all 5 prod robot machines.

We now believe we have solved this problem.  Yay!

**Comment by ndushay** [comment]
FYI, we will be deploying the code that updates dor-services to v5.8.0  to production sometime today or tomorrow, whenever it's convenient.

**Comment by jmartin-sul** [comment]
PR for the common-accessioning dor-services upgrade:  https://github.com/sul-dlss/common-accessioning/pull/62

**Comment by ndushay** [comment]
code deployed;  robots restarted.
