### ISSUE TITLE
Generate techMD only for files that are preserved

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#608]
Currently, we are generating techMD for all files staged during accessioning. This includes files that are shelved and not preserved. We should generate techMD only for files being preserved, as the purpose of the techMD is to track information about files being stored for the long-term.

Example: 

This is a normal (i.e. non-Google) book where the jp2s are generated during assemblyWF and not shelved, and techMD has been generated on all of these files:

https://argo-stage.stanford.edu/view/druid:bs959cg1458?beta=true

**Comment by ndushay** [comment]
this has been done with PR #609
