### ISSUE TITLE
move configs to the private shared_configs repo

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#61]
this would have many benefits, including versioned/backed-up configs in case the current configs got lost or damaged, as well as config consistency across deployed boxes (e.g. the common-accessioning configs currently differ between the `sul-robots1-test` and `sul-robots2-test`, which seems like a bad thing).

**Comment by ndushay** [comment]
I'm closing this as I believe common-accessioning uses shared_configs now.
