### ISSUE TITLE
Handle diacritics in filenames

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#639]
**Describe the bug**
This item is reporting an error in the path to the file:
https://argo.stanford.edu/view/druid:jk443nh6650

`technical-metadata : bad component(expected absolute path component): /dor/workspace/jk/443/nh/6650/jk443nh6650/content/Garges-lès-Gonesse.docx`

Since that is an absolute path and there is a file at that path, I think the problem is likely the diacritic in the file name.

**User Impact**
The item cannot be accessioned as is.

**Expected behavior**
Technical metadata should support a wider range of character sets.

**Additional context**
There are wider problems with character support that might make this item fail elsewhere, but we have to start somewhere with supporting diacritics. Documentation on problematic characters can be found here:

https://consul.stanford.edu/display/chimera/Character+set+constraints+for+SDR+file+names

**Comment by mjgiarlo** [comment]
Moving to In Progress
