### ISSUE TITLE
Workspace cleanup timing out

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#658]
## Backtrace

    line 21 of [PROJECT_ROOT]/lib/robots/dor_repo/accession/end_accession.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/61477729)

**Comment by justinlittman** [comment]
refs https://github.com/sul-dlss/google-books/issues/471

This is being caused by google books remediation, but there nothing extraordinary about the load.

The code is branching and there are http calls to other services, so hard to know where the problem is. Perhaps this should be turned into a job?

**Comment by jcoyne** [comment]
I think the problem here is that DSA can take too long to clean up some objects.  It should be made into an asynchronous API call (like shelve).

**Comment by andrewjbtw** [comment]
I believe this is the same as: https://github.com/sul-dlss/argo/issues/2752
