### ISSUE TITLE
[Uber] Consider switching robot steps to sidekiq

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#662]
This ticket comes out of discussion around https://github.com/sul-dlss/google-books/issues/471

Switching to sidekiq would give us the benefit of automatic retries for workflow steps that encounter transient errors that clear up when the step is simply re-run a few moments later.

If we make this change for all workflow steps, we need to watch out for:

1. Errors that won't clear up with a re-run (i.e. data needs to be fixed before re-run)
2. Steps where re-running after an error results in a new error message that overwrites the original one.

There are probably other things to watch out for. This ticket is to figure that out.

**Comment by ndushay** [comment]
closing in favor of #902;  copied this content there.
