### ISSUE TITLE
Decrease the number of common-accessioning VMs

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#690]
We don't need so many VMs now that we have the tech-metadata on separate machines.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman What should we decrease the number to? Cc: @andrewjbtw

**Comment by justinlittman** [comment]
I think we discussed subtracting one at a time and monitoring.

**Comment by mjgiarlo** [comment]
Thanks, @justinlittman.

@andrewjbtw Are you comfy w/ me putting in a request this week to decommission server `common-accessioning-prod-e` to start this process?

**Comment by andrewjbtw** [comment]
I think that's fine. Because accessioning volume can be so variable, it might take a couple of weeks to see if there's an impact. Or we'll notice with Google right away.

**Comment by mjgiarlo** [comment]
Tracking https://github.com/sul-dlss/operations-tasks/issues/2352 here.

**Comment by ndushay** [comment]
bringing info up to date:

@mjgiarlo: common-accessioning-prod-e is now decommissioned. Let's watch for 2-3 weeks (until early/mid-Oct) and then re-assess.

@andrewjbtw:  perhaps we don't want to go lower

@jcoyne: we could increase on demand if our infrastructure allowed that, e.g. kubernetes.  That would work well because we are very bursty in our usage.

**Comment by ndushay** [comment]
I would say we can resolve.  we can revisit later if we like.  It sounds like our bursts make it a bad idea for it to go lower.  I wonder if we should restore the fifth VM ... @bergeraj have an opinion?

**Comment by andrewjbtw** [comment]
I think we're doing ok with 4 VMs. I haven't seen common-accessioning become a total bottleneck. To the extent that we have any bottlenecks, it's at preservation robots rather than accessioning robots.
