### ISSUE TITLE
[SPIKE] Shelve individual files from preservation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/common-accessioning#754]
This ticket represents a team spike on investigating approaches to https://github.com/sul-dlss/common-accessioning/issues/733.

Considerations:

- [ ] Identify scenarios that are likely be needed
- [ ] Order of where to look for existing files:
  - [ ] Is it in (dor workspace) area? (i.e. "staged")
  - [ ] If not stage, on stacks?
  - [ ] If not on stacks, Is it in preservation?
- [ ] An object’s set of files has contentMetadata settings to show they are in preservation, we know they are there.
- [ ] How do we know if we’re using the latest file?
- [ ] Use computed checksums and compare to contentMetadata (?)
- [ ] What if contentMetadata already thinks its in stacks, but it’s not?

Reference notes doc: https://docs.google.com/document/d/1acAwl49P9eoL0q1-NGd7ALuB49U0eVd0x3icv6sQg4k/edit#

Stretch:  Audit check - Go through contentMetadata, see if each file that is supposed to be on stacks … is there.  Report when not. The goal of this audit is not to create remediation work, but a baseline of missing files (project phoenix objects can likely be ignored as they are certain to have a lot of errors).

**Comment by jcoyne** [comment]
I've done a test setup for this by doing:
```
sdr --service-url https://sdr-api-qa.stanford.edu deposit --label 'hey there' --admin-policy 'druid:zz220zx5298'  --source-id 'test:dark-deposit1' ~/Desktop/Screen\ Shot\ 2021-04-26\ at\ 10.50.50\ AM.png
```
