### ISSUE TITLE
[monitor for problems] decrease robot worker count

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#758]
As discussed earlier this week, in an attempt to alleviate the [sul-dor-prod connection issues](https://github.com/sul-dlss/operations-tasks/issues/2432), we'll try decreasing the number of common-accessioning workers.  I think we'll want to keep an eye out for a few things:
1. robots being unable to keep up with overall accessioning demand due to reduced capacity (bad)
2. robots being unable to move things through at an acceptable rate when accessioning demand is heavier due to reduced concurrency (also bad)
3. a decrease in or elimination of Fedora connection errors as described in the above linked ops issue (good!) (the typical error is running out of outbound connections on dor-services-prod when trying to connect to sul-dor-prod, even after increasing the number of available outbound connections, e.g. [`Errno::EADDRNOTAVAIL: Failed to open TCP connection to sul-dor-prod.stanford.edu:443 (Cannot assign requested address - connect(2) for "sul-dor-prod.stanford.edu" port 443)`](https://app.honeybadger.io/projects/50568/faults/68024987))

The hypothesis is that at peak accessioning times, Fedora's unable to fulfill the demand that common-accessioning robots are placing on it (via dor-services-app) without backing up requests for long enough to exhaust DSA's available outbound connections.  The hope is that we can reduce the peak pressure on Fedora to keep from running out of outbound connections (while also keeping up with overall accessioning demand).  Circumstantial evidence in favor of this approach is that the problem most often coincides with large Argo bulk jobs involving opening/closing SDR objects.

The consensus was that we should decommission one of the four remaining common-accessioning VMs, as we did in #690 last fall.  However, as I went to look up those tickets to see what was done last time, I thought maybe it'd be better to start by decreasing the number of workers in the resque-pool config?  It seems like it'd have roughly the same effect (decreasing the common-accessioning concurrency and thus decreasing the max load common-accessioning can apply to Fedora at once).  But it'd be easier to revert if need be, and would keep us from needing to involve ops.  As another in between possibility, I think we could comment `common-accessioning-prod-d` out of the prod deploy config, kill resque-pool master on `common-accessioning-prod-d`, and then essentially have one of the common-accessioning boxes out of rotation till we add it back to the deployment config (also easier to revert by a single dev than decommissoning).

For now I'll put up a simple PR for decreasing the worker count, but if I'm missing something and we really should just decommission one, I'm happy to file an ops ticket and do the deploy config changes.

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/dor-services-app/issues/2559

**Comment by jmartin-sul** [comment]
worker count decrease (cut 12 common-accessioning workers in #759) has been deployed to prod.

will keep an eye on things over the coming days.

**Comment by jmartin-sul** [comment]
here's a link to a search for the error code we usually see when we run into fedora connection issues:  https://app.honeybadger.io/projects/50568/faults?sort=last_seen_desc&q=-is%3Aresolved%E2%80%81-is%3Aignored%E2%80%81Errno%3A%3AEADDRNOTAVAIL

last prod occurrence as of this comment is 4/28/2021 @ 9:28 AM pacific

**Comment by jmartin-sul** [comment]
we ran into this again at least a couple times this week, including about 11 hours ago, and on monday:
https://app.honeybadger.io/projects/50568/faults/78429481
<img width="1129" alt="Screen Shot 2021-06-25 at 5 24 32 PM" src="https://user-images.githubusercontent.com/7741604/123495845-3abd3f80-d5da-11eb-98d9-04e713498358.png">

https://app.honeybadger.io/projects/50568/faults/80051759
https://app.honeybadger.io/projects/50568/faults/79112695
https://app.honeybadger.io/projects/50568/faults/79112690
https://app.honeybadger.io/projects/50568/faults/67018124

etc: https://app.honeybadger.io/projects/50568/faults?sort=last_seen_desc&q=-is%3Aignored%E2%80%81Errno%3A%3AEADDRNOTAVAIL
<img width="1136" alt="Screen Shot 2021-06-25 at 5 29 14 PM" src="https://user-images.githubusercontent.com/7741604/123496016-e2d30880-d5da-11eb-9676-c31cde6dfd25.png">

**Comment by jmartin-sul** [comment]
Per discussion this morning, next week we'll try dropping the number of common-accessioning workers from 7 down to 5, since we've had no accessioning backlog buildup with the [decrease from 10 to 7 a few weeks ago](https://github.com/sul-dlss/common-accessioning/pull/759/files).

**Comment by jmartin-sul** [comment]
we had two more batches of connection issue this morning (details forthcoming)

**Comment by jmartin-sul** [comment]
small blip just now.  "only" 37 error events this time, afaict (total count in the last hour of the error DSA usually throws).

https://app.honeybadger.io/projects/50568/faults?sort=last_seen_desc&q=-is%3Aignored%E2%80%81Errno%3A%3AEADDRNOTAVAIL

<img width="1158" alt="Screen Shot 2021-07-30 at 3 24 36 PM" src="https://user-images.githubusercontent.com/7741604/127717649-a666be02-5d79-499d-a351-54917e541ebb.png">

**Comment by jmartin-sul** [comment]
per a slack discussion with @andrewjbtw i'm now hesitant to keep pushing in this direction.  i think we can leave the worker counts as-is, unless we start running into issues with an ever-growing accessioning backlog.  but assuming our hypothesis is on the right track, it seems that it's possible to apply sufficient load to fedora from non-accessioning activity, such that this connection exhaustion error still occurs.

https://stanfordlib.slack.com/archives/C09M7P91R/p1628726585190700

@andrewjbtw (wed 2021-08-11, 10 pm)

> Started a close batch of 3000 and Fedora did go out. Here’s what was happening at the time:
> * Close job had closed between 500-1000 druids at that point
> * I was running a bulk update to change the rights on 1000 druids (this is still done in the synchronous, keep your browser open, interface, so I can’t do all of them at once)
> * The batch open for 10,000 druids was still running
> * Google books kicked off another batch
> Since the system went down before even 1000 druids had closed, it looks like you don’t have to be running a large batch to take the system down. You just have to have a few different sustained jobs running at once. 

@andrewjbtw (thu 2021-08-12, 9:30 am)
> Looks like my second batch (of 7000) combined with a release bulk action (also in the 1000s) also ended up taking Fedora down too, but after some cleanup this morning I think everything is through. There was some spillover on Google Books but the good thing about doing this after hours is it doesn't look like anyone else was accessioning.

@jmartin-sul (thu 2021-08-12, 9:50 am)
> nice.  that's not so bad as these outages go, i guess.
>
> unfortunate that the recent common-accessioning worker decrease didn't do anything, but i guess in this case, significant load was being applied by non-accessioning activities.  we can probably leave the counts where they are unless we start running into back log issues, but i'm now hesitant to keep pushing on the worker decrease thing.  am also now out of ideas for easily tweakable things to address this issue.

@andrewjbtw (thu 2021-08-12, 10 am)
> it does feel like changing the worker counts is just something that passes the time while we wait to move off Fedora

**Comment by jcoyne** [comment]
@jmartin-sul the large close job will trigger accessioning, which would be an extra drag on DSA/Fedora.  So I'm not sure why reducing this would not be the right thing.

**Comment by jmartin-sul** [comment]
> @jmartin-sul the large close job will trigger accessioning, which would be an extra drag on DSA/Fedora. So I'm not sure why reducing this would not be the right thing.

ah good point @jcoyne, i think you mentioned that in slack when we were discussing this a few weeks ago, but i'd forgotten.

ok, so maybe we do want to keep pushing in that direction?  should we drop the count by one more per box? 🤷

**Comment by andrewjbtw** [comment]
Reducing the worker count is fine with me since there's no reason to use far more resources than the system really needs. I've just adjusted my expectations since it looks like it only takes a couple of bulk jobs running at the same time to take Fedora down.

**Comment by jmartin-sul** [comment]
as of today, the [most characteristic error](https://app.honeybadger.io/projects/50568/faults?sort=last_seen_desc&q=-is%3Aignored%E2%80%81Errno%3A%3AEADDRNOTAVAIL) (`Errno::EADDRNOTAVAIL`) hasn't been throw in 3 months, so closing this for now.
