### ISSUE TITLE
Fix remediate-object step in common accessioning

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/common-accessioning#77]
This step, described in 

https://consul.stanford.edu/display/chimera/Object+remediation+in+accessioning+-+remediate-object

used to make some minor repairs and model updates to objects when they finally hit accessioning. For instance, a critical one was supplying a missing versionMetadata datastream to legacy objects and to EEMS (and ETDs?).  This seems to stop working sometime in the latter half of 2016, perhaps earlier if it took awhile to investigate a backlog of versioning errors. 

We need to get it working again. We can also clean our remediation code that is no longer needed, as noted on the consul page.

**Comment by cbeer** [comment]
Perhaps as part of https://github.com/sul-dlss/dor-services/pull/260/files?

Can we not just go fix the EEMs and ETD robots to produce well-formed data in the first place?
