### ISSUE TITLE
Keep book reading order the same throughout accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#772]
**Describe the bug**
This item was registered as a book with a right-to-left reading order but after accessioning the reading order had been flipped to left-to-right: https://argo.stanford.edu/view/mr947cp4340 (I've now fixed it, so it's currently right-to-left).

In looking at the object history, I believe the reading order was flipped during the assemblyWF. The [contentMetadata history](https://sul-dor-prod.stanford.edu/fedora/objects/druid:mr947cp4340/datastreams/contentMetadata/history
) shows:

v0: `<bookData readingOrder="rtl"/>` (when registered, no files yet)
v1: `<bookData readingOrder="ltr"/>` (created through accessioning)
v2: `<bookData readingOrder="rtl"/>` (after I flipped the reading order back to right-to-left)

This object was accessioned via Goobi. I checked whether that could be the source of the issue:

- from talking with the digitization lab, this item was in the correct right-to-left reading order in the Goobi app
- Goobi creates a metadata file called "stubContentMetadata.xml" that is sent over with the content files and is used to create contentMetadata during assemblyWF
- the stubContentMetadata.xml for this object is in preservation core and has the correct reading order: `<content type="Book (rtl)">`

This leads me to believe the left-to-right reading order was introduced when the contentMetadata was created during assemblyWF.

**User Impact**
An extra step has to be taken to flip the reading order back to the right direction after accessioning. There are some large projects underway to digitize and accession right-to-left books, so this will slow those projects down by adding an extra step.

**To Reproduce**
I think this is going to happen to all right-to-left books being accessioned via Goobi. A second example with the same issue was accessioned yesterday: https://argo.stanford.edu/view/druid:ff217sb9425

**Expected behavior**
The reading order for books should not change after registration unless a user specifically changes it from the content type menu.

**Additional context**
We added the ability to handle reading order in Argo and Preassembly during the last workcycle. But we did not anticipate this issue, which seems specific to the accessioning path that uses stubContentMetadata.xml, something I think only Goobi does.

**Comment by peetucket** [comment]
I didn't realize the stubContentMetadata.xml made it to preservationcore, but it would be very useful to have that exact file for `druid:mr947cp4340` so I can experiment with it.

**Comment by peetucket** [comment]
I think I've got a fix, but would like to double-check the actual stub content metadata being generated in these cases to verify the value being set in the content type.

**Comment by peetucket** [comment]
Thanks.  Do we know where the "Book (rtl)" comes from in Goobi?  I just want to be sure it is always set like this for RTL books in the stub file coming from Goobi so the trigger works in all cases, and also curious as to what it is LTR books (though that is less important, since we can default to LTR).  Basically, right now, if the content type includes the word "book" in it anywhere, we call it a book.

**Comment by peetucket** [comment]
Actually, I now see the content type of "Book (rtrl)" just gets passed through from the object registered in Argo from the tag we set at registration.  The other choice is "Book (ltr)".  I am fairly confident my PR will work.
