### ISSUE TITLE
expand jp2-create support for images that contain embedded ICC profiles

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#787]
**Describe the bug**
Dozens of druids from the Nuremberg trial archives have failed recently during the jp2-create step. This step creates JP2 derivative files for Stacks from the original source files (usually TIFFs). The failures all result in this error message:

```
jp2-create : JP2 creation command failed: kdu_compress -num_threads 2 -precise -no_weights -quiet Creversible=no Cmodes=BYPASS Corder=RPCL Cblk=\{64,64\} Cprecincts=\{256,256\},\{256,256\},\{128,128\} ORGgen_plt=yes -rate 1.5 Clevels=5 Clayers=6 -i '/imtmp/assembly-image20210809-18016-1yeszl9.tif' -o '/dor/assembly/bs/465/pk/3203/bs465pk3203/content/bs465pk3203_0005.jp2' 2>&1 with result Kakadu Error: The number of colours associated with the colour space identified by the source file (possible from an embedded ICC profile) is not consistent with the number of supplied image components and/or colour palette. You can address this problem by supplying a `-jp2_space' or `-jpx_space' argument to explicitly identify a colour space that has anywhere from 1 to 1 colour components.
```

It is not possible to recover from this error by re-running jp2-create from Argo. Resetting the step may allow the accession to finish, but the resulting object will end up with missing pages in the public display.

I've done a little investigating and I don't think the problem is corrupt or malformed source images. I'm able to open them in Preview and I don't see error messages on the command line when extracting metadata or running imagemagick locally.

The problem seems to be with images that have embedded ICC profiles. I'm not an image expert, so I'm not sure I have much to add about what that means. I'll put example exiftool output for one working image and for one non-working image from the same druid in the comments.

**User Impact**
The only option available to us currently for working around this issue is to:

- re-stage all of the files for the object
- create JP2s from the tiffs before accessioning them (through some ad hoc process)
- run accessioning

For workflows that are entirely internal to SUL, it has generally been possible to work around this issue as above, though it adds a non-trivial amount of work to the process. But the Nuremberg trial archive is a large project where images come from a vendor. At this scale, having to pre-generate the JP2s outside of the SDR accessioning infrastructure is a huge barrier to making progress on the project. I believe the images have already been delivered, so asking for images to be created with different specs does not seem to be an option. 

Accessioning of the Nuremberg documents has been paused since this issue first cropped up in large numbers last week.

**To Reproduce**
1. ssh into a common-accessioning machine
2. run jp2-create manually on a druid that will generate errors
 - `cd common-accessioning/current`
 - `./bin/run_robot -d druid:bs465pk3203 -e production Assembly::Jp2Create`
3. See error

Note that when the jp2-create step is reset it appears to resume from the last image previously processed (based on reading the filenames?) and only stops if it encounters an error. So if it is reset and all remaining images for a given druid can be processed, the step will not hit an error and the object will be accessioned, but the resulting object will be missing pages. Which is to say that resetting this step on the druid in the example above may not hit an error if it the step resumes from a point where it has already passed by the images that will fail.

**Expected behavior**
If a source image is not corrupt or malformed, jp2-create should successfully create a jp2.

**Additional context**
We do not have any analysis tools that I'm aware of that will let us know if a particular image or set of images will be a problem. So we end up not knowing if there is going to be an error until items are already in the workflow. This is out of scope for now, but I would strongly suggest that we find a way to bracket off jp2 creation and possibly the entire assemblyWF from accessioning. In our current workflow architecture, there's no easy way to cancel an accession when images hit errors and we end up accessioning versions that don't work (i.e. are missing pages) just so we can start an accession over again.

**Comment by andrewjbtw** [comment]
Using images from bs465pk3203 as an example:

jp2-create successfully processed the first four images in this druid. The default exiftool output for those images looks like this:

```
ExifTool Version Number         : 12.30
File Name                       : bs465pk3203_0001.tif
Directory                       : .
File Size                       : 8.0 MiB
File Modification Date/Time     : 2010:07:29 12:09:34-07:00
File Access Date/Time           : 2021:08:17 11:32:42-07:00
File Inode Change Date/Time     : 2021:08:17 11:32:23-07:00
File Permissions                : -rwxr-xr-x
File Type                       : TIFF
File Type Extension             : tif
MIME Type                       : image/tiff
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Full-resolution image
Image Width                     : 2314
Image Height                    : 3617
Bits Per Sample                 : 8
Compression                     : Uncompressed
Photometric Interpretation      : BlackIsZero
Strip Offsets                   : 20260
Orientation                     : Horizontal (normal)
Samples Per Pixel               : 1
Rows Per Strip                  : 3617
Strip Byte Counts               : 8369738
X Resolution                    : 300
Y Resolution                    : 300
Resolution Unit                 : inches
Software                        : Adobe Photoshop CS3 Windows
Modify Date                     : 2010:07:29 21:09:36
XMP Toolkit                     : Adobe XMP Core 4.1-c036 46.276720, Mon Feb 19 2007 22:40:08
Native Digest                   : 256,257,258,259,262,274,277,284,530,531,282,283,296,301,318,319,529,532,306,270,271,272,305,315,33432;B8CACD5166E815080D78FD5C9BDF37CA
Creator Tool                    : Adobe Photoshop CS3 Windows
Create Date                     : 2010:07:27 16:00:57+02:00
Metadata Date                   : 2010:07:29 21:09:36+02:00
Format                          : image/tiff
Color Mode                      : Grayscale
History                         : 
Instance ID                     : uuid:940D64D4449BDF119CFD94569CBB6223
IPTC Digest                     : 00000000000000000000000000000000
Displayed Units X               : inches
Displayed Units Y               : inches
Print Style                     : Centered
Print Position                  : 0 0
Print Scale                     : 1
Global Angle                    : 30
Global Altitude                 : 30
Copyright Flag                  : False
URL List                        : 
Slices Group Name               : 162-0734
Num Slices                      : 1
Pixel Aspect Ratio              : 1
Photoshop Thumbnail             : (Binary data 2760 bytes, use -b option to extract)
Has Real Merged Data            : Yes
Writer Name                     : Adobe Photoshop
Reader Name                     : Adobe Photoshop CS3
Color Space                     : Uncalibrated
Exif Image Width                : 2314
Exif Image Height               : 3617
Image Size                      : 2314x3617
Megapixels                      : 8.4
```

Images 5 and 6 (and probably more) do not pass jp2-create. Exiftool output for these images looks like this:

```
ExifTool Version Number         : 12.30
File Name                       : bs465pk3203_0005.tif
Directory                       : .
File Size                       : 5.0 MiB
File Modification Date/Time     : 2010:08:05 05:14:08-07:00
File Access Date/Time           : 2021:08:17 11:34:32-07:00
File Inode Change Date/Time     : 2021:08:17 11:34:31-07:00
File Permissions                : -rwxr-xr-x
File Type                       : TIFF
File Type Extension             : tif
MIME Type                       : image/tiff
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Full-resolution image
Image Width                     : 1841
Image Height                    : 2829
Bits Per Sample                 : 8
Compression                     : Uncompressed
Photometric Interpretation      : BlackIsZero
Make                            : 
Camera Model Name               : 
Strip Offsets                   : 20588
Orientation                     : Horizontal (normal)
Samples Per Pixel               : 1
Rows Per Strip                  : 2829
Strip Byte Counts               : 5208189
X Resolution                    : 300
Y Resolution                    : 300
Resolution Unit                 : inches
Software                        : Adobe Photoshop CS3 Windows
Modify Date                     : 2010:08:05 14:14:09
XMP Toolkit                     : Adobe XMP Core 4.1-c036 46.276720, Mon Feb 19 2007 22:40:08
Native Digest                   : 256,257,258,259,262,274,277,284,530,531,282,283,296,301,318,319,529,532,306,270,271,272,305,315,33432;4EBAC2B69FC6E2AEEF3919CFAD40EA9A
Create Date                     : 2010:08:04 12:41:25+02:00
Metadata Date                   : 2010:08:05 14:14:09+02:00
Creator Tool                    : Adobe Photoshop CS3 Windows
Format                          : image/tiff
Color Mode                      : Grayscale
ICC Profile Name                : Dot Gain 20%
History                         : 
Instance ID                     : uuid:862D70F08AA0DF11B2B7B055968B1C22
IPTC Digest                     : 00000000000000000000000000000000
Displayed Units X               : inches
Displayed Units Y               : inches
Print Style                     : Centered
Print Position                  : 0 0
Print Scale                     : 1
Global Angle                    : 30
Global Altitude                 : 30
Copyright Flag                  : False
URL List                        : 
Slices Group Name               : 162-0738L
Num Slices                      : 1
Pixel Aspect Ratio              : 1
Photoshop Thumbnail             : (Binary data 2083 bytes, use -b option to extract)
Has Real Merged Data            : Yes
Writer Name                     : Adobe Photoshop
Reader Name                     : Adobe Photoshop CS3
Color Space                     : Uncalibrated
Exif Image Width                : 1841
Exif Image Height               : 2829
Profile CMM Type                : Adobe Systems Inc.
Profile Version                 : 2.1.0
Profile Class                   : Output Device Profile
Color Space Data                : GRAY
Profile Connection Space        : XYZ
Profile Date Time               : 1999:06:03 00:00:00
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : none
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Media-Relative Colorimetric
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Adobe Systems Inc.
Profile ID                      : 0
Profile Copyright               : Copyright 1999 Adobe Systems Incorporated
Profile Description             : Dot Gain 20%
Media White Point               : 0.9642 1 0.82491
Media Black Point               : 0 0 0
Gray Tone Reproduction Curve    : (Binary data 524 bytes, use -b option to extract)
Image Size                      : 1841x2829
Megapixels                      : 5.2
```

Going by the field names, there are no exiftool output fields unique to `bs465pk3203_0001.tif`. But for `bs465pk3203_0005.tif` there are a number of unique fields, many of which appear to be related to the embedded profile:

```
CMM Flags                       
Camera Model Name               
Color Space Data                
Connection Space Illuminant     
Device Attributes               
Device Manufacturer             
Device Model                    
Gray Tone Reproduction Curve    
ICC Profile Name                
Make                            
Media Black Point               
Media White Point               
Primary Platform                
Profile CMM Type                
Profile Class                   
Profile Connection Space        
Profile Copyright               
Profile Creator                 
Profile Date Time               
Profile Description             
Profile File Signature          
Profile ID                      
Profile Version                 
Rendering Intent       
```

**Comment by jcoyne** [comment]
Is this a bug in kakadu?

> Kakadu Error: The number of colours associated with the colour space identified by the source file (possible from an embedded ICC profile) is not consistent with the number of supplied image components and/or colour palette. You can address this problem by supplying a `-jp2_space' or `-jpx_space' argument to explicitly identify a colour space that has anywhere from 1 to 1 colour components.


Or are we supposed to explicitly pass an argument to identifiy a color space? If the latter, how do we derive this? I don't know a lot about kakadu.

**Comment by andrewjbtw** [comment]
My understanding of the jp2-create step is that it works like this:

1. takes an input TIFF
2. creates a temporary, normalized TIFF in the /imtmp directory of the common-accessioning machine that is running the step
3. creates a JP2 from that temporary TIFF and places it in the `content` folder for the druid in the `/dor/assembly` druid tree
4. does this for each TIFF
5. when done, adds the JP2s to the contentMetadata.xml

One option that I think @calavano has suggested before may be to make sure that normalized temporary tiff can be processed by kakadu. Maybe by removing the profile?

**Comment by andrewjbtw** [comment]
@jcoyne I'm not sure if there's a bug. I think there's a policy issue involved where some options are free and some are non-free, and the free options don't cover all of the JP2 or JPX possibilities.

**Comment by calavano** [comment]
@andrewjbtw  @jcoyne  Our jp2-create process should work with images with embedded ICC profiles in most cases. We've had errors like this in the past when an embedded ICC profile for the image didn't match the color data. This would be something like an sRGB ICC profile incorrectly embedded into an Grayscale or CMYK image or if exiftool incorrectly read the image header incorrectly guessing the number of color channels.

The jp2-create process should take the input image, create a temporary TIFF file, and then create the jp2 from that temporary TIFF. We do this because the Kakadu binaries that we use need an uncompressed TIFF as an input.

We also need to normalize the color profile of color images to be sRGB. The gem should take the embedded color profile of the input image and normalize it to sRGB. My understanding is that the JPEG2000 specs only support a small number if ICC profiles in Part 1 of the spec and you need to use Part 2 of the spec to make use of arbitrary embedded ICC profiles. Only Part 1 of the spec is in the "free" category, while the rest is potentially patent encumbered. Certain uses of Part 2 of the spec would technically call for labeling the files as .jpx instead of .jp2.

In the case of `bs465pk3203_0004.tif` converting and `bs465pk3203_0005.tif` failing, the main difference is that `bs465pk3203_0004.tif` doesn't have a color profile and `bs465pk3203_0005.tif` does. The color profile in `bs465pk3203_0005.tif` is the 'Dot Gain 20%' one, which is a good profile for a single channel file. I would expect this to convert correctly. On a local machine I'm able to use the assembly-image gem to create a jp2 without error. I would wonder if it is the result in different versions one of the pieces in the chain.

I thought that the gem would only try to use the profile conversion switch with color images, but looking at the code I think it always attempts it when a profile is present. Some things to check would be 1) make sure the gem isn't creating a temporary single-channel TIFF with an sRGB color profile, and 2) make sure the gem isn't incorrectly reading the input image and producing a bad temporary TIFF. It's odd that it is working on my local machine. I can do some tests to see if I can force the error.

**Comment by andrewjbtw** [comment]
When you say the conversion works on your local machine, do you mean the whole chain of: source tiff --> temporary tiff --> jp2?

**Comment by calavano** [comment]
Yes, this is taking the original tiff and converting using the gem.

Just doing:
```
require 'assembly-image'
image = Assembly::Image.new('bs465pk3203_0005.tif')
image.create_jp2
``` 
It does look like it called ImageMagick with the profile flag to try and convert to sRGB. I just edited the gem to print out the convert command here:
```
MAGICK_TEMPORARY_PATH=/tmp convert -quiet -compress none -limit memory 1GiB -limit map 1GiB -depth 8 -type Grayscale -profile /home/calavt/.rvm/gems/ruby-2.7.2/gems/assembly-image-1.7.7/profiles/DotGain20.icc -profile /home/calavt/.rvm/gems/ruby-2.7.2/gems/assembly-image-1.7.7/profiles/sRGBIEC6196621.icc 'bs465pk3203_0005.tif[0]' '/tmp/assembly-image20210818-1752192-1xl9gg.tif'
```

However it doesn't look like it actually carries over the ICC profile to the temporary TIFF on my machine:
```
$ exiftool /tmp/assembly-image20210818-1752192-1xl9gg.tif  | grep "ICC Profile Name"
ICC Profile Name                : Dot Gain 20%
```

In case it is useful:
```
$ convert -version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org

$ exiftool -ver
11.88
```

**Comment by andrewjbtw** [comment]
If the problem comes down to the tool versions, I wonder if this is a side effect of the change we recently made to update both stage and prod to use the same versions of the image processing tools. If that's the case, I wonder if we should reverse the change in https://github.com/sul-dlss/operations-tasks/issues/2699

I just ran exiftool on Nuremberg items that previously passed accessioning and found that page 82 of https://argo.stanford.edu/view/mv519ng0713 has an ICC profile. This druid was accessioned successfully in late July, a few days before we upgraded imageMagick and libtiff.

I took the same files and just ran them in stage and page 82 ended up in an error:
https://argo-stage.stanford.edu/view/druid:cd584jp9686

So that suggests the problem is related to tool versions and that we also do not have a good way to tell whether an upgrade will cause problems. I tested with a lot of images before that upgrade and did not see this issue.

**Comment by andrewjbtw** [comment]
FWIW, these are the tool versions in common-accessioning:

**In prod**

Exiftool
```
$ exiftool -ver
11.01
```
ImageMagick
```
$ convert -version
Version: ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
```
kdu_compress
```
$ kdu_compress -v
This is Kakadu's "kdu_compress" application.
    Compiled against the Kakadu core system, version v7.10.2
    Current core system version is v7.10.2```
```
libtiff
```
$ rpm -q libtiff
libtiff-4.0.3-35.el7.x86_64
```

**In stage**

Exiftool
```
$ exiftool -ver
11.70
```
ImageMagick
```
$ convert -version
Version: ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
```
kdu_compress
```
$ kdu_compress -version
This is Kakadu's "kdu_compress" application.
    Compiled against the Kakadu core system, version v7.10.2
    Current core system version is v7.10.2
```
libtiff
```
$ rpm -q libtiff
libtiff-4.0.3-35.el7.x86_64
```

**Comment by andrewjbtw** [comment]
Since Tony's analysis pointed to issues with the tool versions, we reversed the recent upgrades to imagemagick and libtiff (see https://github.com/sul-dlss/operations-tasks/issues/2727 ) and this has made it possible to get the Nuremberg items moving again.

I'd still like to improve this step in the future since we're now in a situation where we may not be able to upgrade without breaking something. But since there's nothing more to do at the moment I'm going to close this issue.
