### ISSUE TITLE
File access mapping error

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#843]
https://argo-qa.stanford.edu/view/druid:dh159yz4449 is failing the content metadata wf step. When the JSON is parsed locally, the error is:
```
Cocina::Models::ValidationError ({"access"=>"citation-only", "download"=>"none"} isn't one of in #/components/schemas/FileAccess)
```

In fact, citiation-only is not valid file access. This is because the file access is being taken from the object access, where citation-only is valid: https://github.com/sul-dlss/common-accessioning/blob/main/lib/dor/file_sets.rb#L91

Valid object access:
```
        - $ref: '#/components/schemas/DarkAccess'
        - $ref: '#/components/schemas/CitationOnlyAccess'
        - $ref: '#/components/schemas/ControlledDigitalLendingAccess'
        - $ref: '#/components/schemas/LocationBasedAccess'
        - $ref: '#/components/schemas/LocationBasedDownloadAccess'
        - $ref: '#/components/schemas/StanfordAccess'
        - $ref: '#/components/schemas/WorldAccess'
```

Valid file access:
```
        - $ref: '#/components/schemas/DarkAccess'
        - $ref: '#/components/schemas/ControlledDigitalLendingAccess'
        - $ref: '#/components/schemas/LocationBasedAccess'
        - $ref: '#/components/schemas/LocationBasedDownloadAccess'
        - $ref: '#/components/schemas/StanfordAccess'
        - $ref: '#/components/schemas/WorldAccess'
 ```

It appears the only difference is CitationOnlyAccess. See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/file_sets.rb#L112-L118 for the correct handling.

**Comment by jcoyne** [comment]
I suspect that if the item is "citation" then the files should be:

```json
{
    "access": "dark",
    "download": "none"
}
```                  


This is how all the google books objects are anyway.

**Comment by andrewjbtw** [comment]
I missed this conversation when Outlook threw out my github notification email filters, but yes, we ended up mapping object-level "citation" to file-level "dark,none" last year. It's not perfect but it has been working as a mapping with the Fedora model. In a fully Cocina world (including Purl), maybe there will be a better solution.
