### ISSUE TITLE
Items with multiple Project tags cannot complete the accessionWF

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/common-accessioning#851]
Items with multiple project tags are not completing the accessionWF. A Goobi accessioning batch ran into this today. My guess is that the error is hitting when the contentMetadata.xml is being read into Cocina.

HB
https://app.honeybadger.io/projects/52894/faults/84318728 (common-accessioning)
https://app.honeybadger.io/projects/50568/faults/84317662 (dor-services-app)

See also:
https://github.com/sul-dlss/dor-services-app/issues/3004
https://github.com/sul-dlss/dor-services-app/issues/3545

This is a more serious issue than the known issue around running the releaseWF with multiple Project tags.

**Comment by peetucket** [comment]
@jcoyne and @andrewjbtw : is this resolved and can be close this ticket now?

**Comment by jcoyne** [comment]
Yes.
