### ISSUE TITLE
RuntimeError: can't find reading direction in contentMetadata.xml

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#866]
## Backtrace

    line 23 of [PROJECT_ROOT]/lib/dor/viewing_direction_helper.rb: viewing_direction
    line 66 of [PROJECT_ROOT]/lib/dor/structural_metadata.rb: create_member_order
    line 55 of [PROJECT_ROOT]/lib/dor/structural_metadata.rb: build_has_member_orders

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/84766044)

![image](https://user-images.githubusercontent.com/96775/161316657-a4de58a7-67b3-4eb6-9417-f97a2bfdef83.png)

**Comment by ndushay** [comment]
@andrewjbtw  - my analysis:

1.  the honeybadger ERROR is at the wrong status level.  We can change it to a WARNING notificaton.  There is already code to set it to "left-to-right" if it is missing ... but because we raise an error, we just stop on those objects.

2  the code change that caused this MAY be:

https://github.com/sul-dlss/common-accessioning/commit/8b2536adcb703631012723f856648c70614964bd

it is only looking for the reading direction in this spot in contentMetadata.xml:

`reading_direction = ng_xml.xpath('//bookData/@readingOrder').first&.value`

Would we ever need to look for it in another spot in the contentMetadata (like, something that wouldn't have "bookData" in contentMetadata?)

**Comment by andrewjbtw** [comment]
I don't think the problem was where it was looking. There was no readingOrder in the contentMetadata.xml. For both druids with the error, I pasted it in manually by editing the files on the /dor filesystem so that they would finish accessioning. 

As far as I know, that's the only way readingOrder is expressed in the XML.

**Comment by ndushay** [comment]
Andrew and I spoke, and we believe there are 2 things to address:

1.  for common-accessioning `[lib/dor/structural_metadata.rb](https://github.com/sul-dlss/common-accessioning/blob/main/lib/dor/viewing_direction_helper.rb)` -- instead of raisiing an error, we want to WARN in honeybadger, default to left-to-right, and continue processing.  A PR for this will be forthcoming.

2.  in pre-assembly, we believe the problem is when file_manifest is used for an object type that have have a reading direction (book, manuscript) (and maybe type checking is strict?).   We do not have a test case in preassembly for a book or manuscript.   Andrew is going to create some test data for this and I will write a spec and correct the probem in pre-assembly, assuming this is where the logic is missing.

**Comment by ndushay** [comment]
leaving this open until pre-assembly fix is also done.

**Comment by jcoyne** [comment]
@ndushay why is this reopened? Were the fixes that pointed at this wrong or incomplete?

**Comment by ndushay** [comment]
a mistake.
