### ISSUE TITLE
Shelve robot - Assert permissions in stacks rather than passing through source permissions

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#88]
Recently a set of objects were accessioned, and when shelved they had insufficient permissions for delivery -- `rw-r-----` instead of `-rw-r--r--`.  We believe this is because permissions from the source were copied forward through the processing chain though to the Digital Stacks.  This has apparently not been an issue overall but these were much older DPG objects finally being processed.

Shelve should set the proper permissions explicitly to guarantee consistency.

**Comment by blalbrit** [comment]
This continues to be an issue with third-party content and some content produced within Green.

**Comment by blalbrit** [comment]
We are also seeing some ETDs come in in this state, per @caaster

**Comment by aaron-collier** [comment]
Requires updating dor-services

**Comment by aaron-collier** [comment]
Requires https://github.com/sul-dlss/dor-services/issues/411
