### ISSUE TITLE
EPIC: clean up (symlinks, etc.) after acccesioning completes

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#901]
One of the DOR folders is not cleaned up properly

- We do clean up files properly
    - but see issue #907
- We end up with broken symlinks that should be deleted

See sul-dlss/argo#321

**Comment by ndushay** [comment]
@andrewjbtw do you know if this has been addressed?

**Comment by andrewjbtw** [comment]
I still need to confirm in prod. I think so, but prod still has some data from before we made this change and I need to clean that up manually. Once I've done that, it will be easy to see if this is working as expected.
