### ISSUE TITLE
EPIC: reset stage/qa in a repeatable, documented approach

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#908]
Should include:
- removing data from postgresdb
- removing data from disk space (e.g. /dor for accessioning, /stacks, /web-archiving-stacks, /preservation)
- removing data from SDR Solr index
- removing data from prescat
- removing data from tech-md-service ...
- workflows?
- google books?
etc.

All steps should be documented.  Scripts are welcome, but keep in mind this isn't done that often, so documenting how to do it may be a better approach than trying to write one rake task/script to do the whole thing.  Code to help with onerous pieces may make sense.

**Comment by ndushay** [comment]
@jcoyne at this time, we don't coord our test data with access, so we can leave that alone.  Similarly for libsys and the ILS.  I pondered sdr-api, h2 and hydra-etd briefly;  I did put question marks by some of the apps I listed.  

I'm not sure exactly where the line should be, but IMO it shouldn't involve Andrew having to fuss around hand removing files from NFS mounts, nor going through lots of machinations to test if a process works across our apps, e.g.:   ingesting a web-archiving collection update;  ingesting media files, updating an etd, whatever ... on stage (and qa).

**Comment by andrewjbtw** [comment]
We should check with Amy on resetting h2-stage. But either we have to reset that if we reset related data in DOR and preservation or we have to exclude any H2 item during a reset. I'm not hugely concerned with the volume of data from H2-stage.

**Comment by mjgiarlo** [comment]
Superseded by https://github.com/sul-dlss/argo/issues/3947
