### ISSUE TITLE
contentMetadata robot can handle json fragment of cocina structural

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#913]
Once preassembly is producing structural json, the contentMetadata robot needs to be able to:

- check if there is structural json fragment
    - if so, use it instead of contentMetadata.xml (See NOTE)
    - if not, look for contentMetadata.xml and proceed as it works now.

NOTE:  at first, I think we may want a way to vet that the structural json fragment results in the same think in the ultimate cocina object as the contentMetadata.xml would.   Not sure of the best way to do this.  Specs?   some sort of temporary duel processing paths with a crosswalk comparing the results?

**Comment by ndushay** [comment]
> Can preassembly use the DOR-services api rather than write a piece of json? Then the robot step can skip if no contentMetadata is present.

@jcoyne this is an intriguing idea ... can you say more?

Isn't the idea of preassembly that it's turning a csv and a directory structure with files into contentMetadata?   How would we get that processed info in the right shape to send to DSA without ... essentially doing all the work already?

**Comment by jcoyne** [comment]
Yes, that's what I'm saying. Preassembly can do all the work right away. Why do we want to have 2 steps?  That's more complicated and more room for error.
