### ISSUE TITLE
assemblyWF should operate on cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#918]
Presently it mutates the contentMetadata.xml file on the disk.  Instead, it can convert contentMetadata.xml to cocina in Assembly::ContentMetadataCreate and then use that subsequently.

**Comment by ndushay** [comment]
This can be worked on now;  it can't be merged until sul-dlss/pre-assembly#949 is deployed.

**Comment by ndushay** [comment]
ok!
