### ISSUE TITLE
Add contentMetadata check for file names with slashes

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/common-accessioning#93]
This implies an object assembled with the content found in sub-directories. While in principle there is nothing wrong with structured content grouped in directories -- they flow through the system and are supported in Moab -- we require a flat representation of content for access and delivery. So we need to enforce this before ingesting.  File names in contentMetadata should not be allowed to contain a slash.

The use of sub-directories seems to originate in some assembly scenarios. Putting a check here lets us detect the problem both at initial assembly and at any future versioning.

**Comment by ndushay** [comment]
@andrewjbtw is this still a problem?

**Comment by andrewjbtw** [comment]
I'm pretty sure it's a problem but a different kind of problem now since we aren't using a datastream. I'll write up a different ticket or tickets - I think preassembly needs to check for this if it doesn't already. I'll close this when the other tickets are linked to it.

**Comment by andrewjbtw** [comment]
We now support hierarchy so this isn't a problem anymore.
