### ISSUE TITLE
Address performance problems with libvips

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#944]
As this time, stage and qa both have common-accessioning deployed with libvips (and prod does NOT) to allow for load testing and fixing the performance problems we had with libvips.

Note: 
- TMPDIR envvar was set on common-accessioning VMS in puppet PR sul-dlss/puppet/pull/8327
- VIPS_DISC_THRESHOLD envvar is posed to be set in puppet PR sul-dlss/puppet/pull/8335

Let us know how else we can help;  assigning this to Andrew and Tony Calavano.

**Comment by andrewjbtw** [comment]
Is there an action on this ticket? Just testing?

**Comment by justinlittman** [comment]
Why change `VIPS_DISC_THRESHOLD`? It seems that it changes one problem (running out of disk space) into two (running out of RAM and disk space).

Is there a way of reproducing the problem?

**Comment by ndushay** [comment]
The action for this ticket is:
- [ ] see if you can trigger performance problems on stage by mimicking what was happening in prod
- [ ] debug errors
- [ ] repeat until we don't get errors
- [ ] notify Naomi or someone that we are ready to try libvips in prod again (requires a Gemfile tweak, is all)

**Comment by ndushay** [comment]
Andrew just said he was unable to cause errors in stage, so we're going to try deploying common-accessioning with libvips to prod ...

**Comment by ndushay** [comment]
I am closing this ticket.
