### ISSUE TITLE
Add gis locations to the clean-up step

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#98]
Currently, cleaning up the gis data that is in the temp assembly space is a manual job. We would like to add the gis assembly endpoint to the clean-up step so that it removes content from that location after ingest to preservation core just as is currently done with /dor/workspace and /dor/assembly.

**Comment by ndushay** [comment]
@andrewjbtw is this still a problem?

**Comment by andrewjbtw** [comment]
I don't know. I'll see if I can figure that out.

**Comment by edsu** [comment]
It seems like this can be closed now that we have https://github.com/sul-dlss/gis-robot-suite/pull/852 ?

**Comment by andrewjbtw** [comment]
It might even have been closeable before. I never did work out whether the ticket was still needed.
